/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminView.java
 *
 * Created on 06.nov.2011, 13:44:26
 */
package pizzaprogram.gui.views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bart
 */
public class AdminView extends javax.swing.JPanel {

    /** Creates new form AdminView */
    public AdminView() {
        initComponents();
    }
    
    public String toString()
    {
        return "AdminView";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        CustomerEditingJPanel = new javax.swing.JPanel();
        editCustomerMainSplitPane = new javax.swing.JSplitPane();
        customerEditCustomerListPanel = new javax.swing.JPanel();
        allCustomersTableScrollPane = new javax.swing.JScrollPane();
        allActiveCustomersTable = new javax.swing.JTable();
        searchCustomerButton = new javax.swing.JButton();
        searchCustomerTextBox = new javax.swing.JTextField();
        addNewCustomerButton = new javax.swing.JButton();
        customerEditDeleteSelectedCustomerButton = new javax.swing.JButton();
        editCustomerEditScrollPane = new javax.swing.JScrollPane();
        editCustomerEditPanel = new javax.swing.JPanel();
        editCustomerFirstNameLabel = new javax.swing.JLabel();
        customerEditFirstNameTextBox = new javax.swing.JTextField();
        editCustomerLastNameLabel = new javax.swing.JLabel();
        customerEditCityTextBox = new javax.swing.JTextField();
        editCustomerAddressLabel = new javax.swing.JLabel();
        customerEditPostalCodeTextBox = new javax.swing.JTextField();
        editCustomerPostalCodeLabel = new javax.swing.JLabel();
        editCustomerCityLabel = new javax.swing.JLabel();
        editCustomerPhoneNumberLabel = new javax.swing.JLabel();
        editCustomerCommentsLabel = new javax.swing.JLabel();
        customerEditAddressTextBox = new javax.swing.JTextField();
        customerEditLastNameTextBox = new javax.swing.JTextField();
        customerEditPhoneNumberTextBox = new javax.swing.JTextField();
        customerEditResetChangesButton = new javax.swing.JButton();
        customerEditConfirmChangesButton = new javax.swing.JButton();
        editCustomerCommentsTextAreaScrollPane = new javax.swing.JScrollPane();
        customerEditCommentsTextArea = new javax.swing.JTextArea();
        DishEditingPanel = new javax.swing.JPanel();
        editDishesMainSplitPane = new javax.swing.JSplitPane();
        dishEditDishListJPanel = new javax.swing.JPanel();
        allActiveDishesDishTableScrollPane = new javax.swing.JScrollPane();
        allActiveDishesTable = new javax.swing.JTable();
        searchDishSearchButton = new javax.swing.JButton();
        searchDishTextBox = new javax.swing.JTextField();
        addNewDishButton = new javax.swing.JButton();
        editDishScrollPane = new javax.swing.JScrollPane();
        editDishJPanel = new javax.swing.JPanel();
        dishEditNameLabel = new javax.swing.JLabel();
        editDishNameTextBox = new javax.swing.JTextField();
        dishEditDescriptionLabel = new javax.swing.JLabel();
        editDishDescriptionScrollPane = new javax.swing.JScrollPane();
        editDishDescriptionTextArea = new javax.swing.JTextPane();
        dishEditPriceLabel = new javax.swing.JLabel();
        dishIsVegetarianLabel = new javax.swing.JLabel();
        editDishIsVegetarianComboBox = new javax.swing.JComboBox();
        dishEditIsPSpicyLabel = new javax.swing.JLabel();
        editDishIsPsicyComboBox = new javax.swing.JComboBox();
        editDIshContainsNutsComboBox = new javax.swing.JComboBox();
        dishEditContainsNutsLabel = new javax.swing.JLabel();
        editDishContainsDairyComboBox = new javax.swing.JComboBox();
        dishEditContainsDairyLabel = new javax.swing.JLabel();
        editDIshContainsGlutenComboBox = new javax.swing.JComboBox();
        dishEditContainsGlutenLabel = new javax.swing.JLabel();
        dishEditIsActiveLabel = new javax.swing.JLabel();
        editDishIsDishActiveComboBox = new javax.swing.JComboBox();
        confirmDishEditButton = new javax.swing.JButton();
        editDishDishPriceTextArea = new javax.swing.JTextField();
        ExtrasEditingPanel = new javax.swing.JPanel();
        extrasMainSplitPane = new javax.swing.JSplitPane();
        editExtraJPanel = new javax.swing.JPanel();
        extraEditNameLabel = new javax.swing.JLabel();
        editExtraExtraNameTextBox = new javax.swing.JTextField();
        extraEditPriceTextBox = new javax.swing.JLabel();
        editExtraIsActiveLabel = new javax.swing.JLabel();
        editExtraExtraIsActiveComboBox = new javax.swing.JComboBox();
        confirmEditExtraButton = new javax.swing.JButton();
        editExtraExtraPriceTextArea = new javax.swing.JTextField();
        editExtraExtraSelectionJPanel = new javax.swing.JPanel();
        allRegisteredExtrasScrollPane = new javax.swing.JScrollPane();
        allRegisteredExtrasTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        searchExtraSearchButton = new javax.swing.JButton();
        searchExtraTextBox = new javax.swing.JTextField();
        createNewExtraButton = new javax.swing.JButton();
        settingsScrollPane = new javax.swing.JScrollPane();
        editSettingsJPanel = new javax.swing.JPanel();
        editSettingsNameOfRestaurantLabel = new javax.swing.JLabel();
        settingsEditNameOfRestaurantTextBox = new javax.swing.JTextField();
        editSettingsMinimumOrderPriceLabel = new javax.swing.JLabel();
        settingsEditMinimumPriceFreeDeliveryTextBox = new javax.swing.JTextField();
        editSettingsDeliveryPriceLabel = new javax.swing.JLabel();
        settingsDeliveryPriceTextBox = new javax.swing.JTextField();
        settingsApplyChangesButton = new javax.swing.JButton();
        settingsResetSettingsButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainTabbedPane.setName("mainTabbedPane"); // NOI18N

        CustomerEditingJPanel.setName("CustomerEditingJPanel"); // NOI18N

        editCustomerMainSplitPane.setDividerLocation(400);
        editCustomerMainSplitPane.setName("editCustomerMainSplitPane"); // NOI18N

        customerEditCustomerListPanel.setName("customerEditCustomerListPanel"); // NOI18N

        allCustomersTableScrollPane.setName("allCustomersTableScrollPane"); // NOI18N

        allActiveDishesTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        allActiveCustomersTable.setAutoCreateRowSorter(true);
        allActiveCustomersTable.setModel(new DefaultTableModel());
        allActiveCustomersTable.setName("allActiveCustomersTable"); // NOI18N
        allCustomersTableScrollPane.setViewportView(allActiveCustomersTable);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getResourceMap(AdminView.class);
        searchCustomerButton.setText(resourceMap.getString("searchCustomerButton.text")); // NOI18N
        searchCustomerButton.setName("searchCustomerButton"); // NOI18N

        searchCustomerTextBox.setName("searchCustomerTextBox"); // NOI18N

        addNewCustomerButton.setText(resourceMap.getString("addNewCustomerButton.text")); // NOI18N
        addNewCustomerButton.setName("addNewCustomerButton"); // NOI18N

        customerEditDeleteSelectedCustomerButton.setText(resourceMap.getString("customerEditDeleteSelectedCustomerButton.text")); // NOI18N
        customerEditDeleteSelectedCustomerButton.setName("customerEditDeleteSelectedCustomerButton"); // NOI18N

        javax.swing.GroupLayout customerEditCustomerListPanelLayout = new javax.swing.GroupLayout(customerEditCustomerListPanel);
        customerEditCustomerListPanel.setLayout(customerEditCustomerListPanelLayout);
        customerEditCustomerListPanelLayout.setHorizontalGroup(
            customerEditCustomerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerEditCustomerListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewCustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(searchCustomerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCustomerButton)
                .addContainerGap())
            .addComponent(allCustomersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
            .addGroup(customerEditCustomerListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerEditDeleteSelectedCustomerButton)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        customerEditCustomerListPanelLayout.setVerticalGroup(
            customerEditCustomerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerEditCustomerListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerEditCustomerListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewCustomerButton)
                    .addComponent(searchCustomerButton)
                    .addComponent(searchCustomerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allCustomersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerEditDeleteSelectedCustomerButton)
                .addGap(4, 4, 4))
        );

        editCustomerMainSplitPane.setLeftComponent(customerEditCustomerListPanel);

        editCustomerEditScrollPane.setName("editCustomerEditScrollPane"); // NOI18N

        editCustomerEditPanel.setName("editCustomerEditPanel"); // NOI18N

        editCustomerFirstNameLabel.setText(resourceMap.getString("editCustomerFirstNameLabel.text")); // NOI18N
        editCustomerFirstNameLabel.setName("editCustomerFirstNameLabel"); // NOI18N

        customerEditFirstNameTextBox.setText(resourceMap.getString("customerEditFirstNameTextBox.text")); // NOI18N
        customerEditFirstNameTextBox.setName("customerEditFirstNameTextBox"); // NOI18N

        editCustomerLastNameLabel.setText(resourceMap.getString("editCustomerLastNameLabel.text")); // NOI18N
        editCustomerLastNameLabel.setName("editCustomerLastNameLabel"); // NOI18N

        customerEditCityTextBox.setName("customerEditCityTextBox"); // NOI18N

        editCustomerAddressLabel.setText(resourceMap.getString("editCustomerAddressLabel.text")); // NOI18N
        editCustomerAddressLabel.setName("editCustomerAddressLabel"); // NOI18N

        customerEditPostalCodeTextBox.setName("customerEditPostalCodeTextBox"); // NOI18N

        editCustomerPostalCodeLabel.setText(resourceMap.getString("editCustomerPostalCodeLabel.text")); // NOI18N
        editCustomerPostalCodeLabel.setName("editCustomerPostalCodeLabel"); // NOI18N

        editCustomerCityLabel.setText(resourceMap.getString("editCustomerCityLabel.text")); // NOI18N
        editCustomerCityLabel.setName("editCustomerCityLabel"); // NOI18N

        editCustomerPhoneNumberLabel.setText(resourceMap.getString("editCustomerPhoneNumberLabel.text")); // NOI18N
        editCustomerPhoneNumberLabel.setName("editCustomerPhoneNumberLabel"); // NOI18N

        editCustomerCommentsLabel.setText(resourceMap.getString("editCustomerCommentsLabel.text")); // NOI18N
        editCustomerCommentsLabel.setName("editCustomerCommentsLabel"); // NOI18N

        customerEditAddressTextBox.setName("customerEditAddressTextBox"); // NOI18N

        customerEditLastNameTextBox.setName("customerEditLastNameTextBox"); // NOI18N

        customerEditPhoneNumberTextBox.setText(resourceMap.getString("customerEditPhoneNumberTextBox.text")); // NOI18N
        customerEditPhoneNumberTextBox.setName("customerEditPhoneNumberTextBox"); // NOI18N

        customerEditResetChangesButton.setText(resourceMap.getString("customerEditResetChangesButton.text")); // NOI18N
        customerEditResetChangesButton.setName("customerEditResetChangesButton"); // NOI18N

        customerEditConfirmChangesButton.setText(resourceMap.getString("customerEditConfirmChangesButton.text")); // NOI18N
        customerEditConfirmChangesButton.setName("customerEditConfirmChangesButton"); // NOI18N

        editCustomerCommentsTextAreaScrollPane.setName("editCustomerCommentsTextAreaScrollPane"); // NOI18N

        customerEditCommentsTextArea.setColumns(20);
        customerEditCommentsTextArea.setLineWrap(true);
        customerEditCommentsTextArea.setRows(5);
        customerEditCommentsTextArea.setName("customerEditCommentsTextArea"); // NOI18N
        editCustomerCommentsTextAreaScrollPane.setViewportView(customerEditCommentsTextArea);

        javax.swing.GroupLayout editCustomerEditPanelLayout = new javax.swing.GroupLayout(editCustomerEditPanel);
        editCustomerEditPanel.setLayout(editCustomerEditPanelLayout);
        editCustomerEditPanelLayout.setHorizontalGroup(
            editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editCustomerEditPanelLayout.createSequentialGroup()
                        .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editCustomerPostalCodeLabel)
                            .addComponent(editCustomerPhoneNumberLabel)
                            .addComponent(editCustomerFirstNameLabel)
                            .addComponent(editCustomerAddressLabel)
                            .addComponent(editCustomerLastNameLabel)
                            .addComponent(editCustomerCityLabel)
                            .addComponent(editCustomerCommentsLabel))
                        .addGap(18, 18, 18)
                        .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerEditFirstNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(customerEditLastNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(customerEditAddressTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(customerEditCityTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(customerEditPostalCodeTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(customerEditPhoneNumberTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(editCustomerCommentsTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(editCustomerEditPanelLayout.createSequentialGroup()
                        .addComponent(customerEditResetChangesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerEditConfirmChangesButton)
                        .addContainerGap())))
        );
        editCustomerEditPanelLayout.setVerticalGroup(
            editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerFirstNameLabel)
                    .addComponent(customerEditFirstNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerLastNameLabel)
                    .addComponent(customerEditLastNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerAddressLabel)
                    .addComponent(customerEditAddressTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerCityLabel)
                    .addComponent(customerEditCityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerPostalCodeLabel)
                    .addComponent(customerEditPostalCodeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomerPhoneNumberLabel)
                    .addComponent(customerEditPhoneNumberTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editCustomerCommentsLabel)
                    .addComponent(editCustomerCommentsTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerEditResetChangesButton)
                    .addComponent(customerEditConfirmChangesButton))
                .addContainerGap())
        );

        editCustomerEditScrollPane.setViewportView(editCustomerEditPanel);

        editCustomerMainSplitPane.setRightComponent(editCustomerEditScrollPane);

        javax.swing.GroupLayout CustomerEditingJPanelLayout = new javax.swing.GroupLayout(CustomerEditingJPanel);
        CustomerEditingJPanel.setLayout(CustomerEditingJPanelLayout);
        CustomerEditingJPanelLayout.setHorizontalGroup(
            CustomerEditingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editCustomerMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        CustomerEditingJPanelLayout.setVerticalGroup(
            CustomerEditingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editCustomerMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("CustomerEditingJPanel.TabConstraints.tabTitle"), CustomerEditingJPanel); // NOI18N

        DishEditingPanel.setName("DishEditingPanel"); // NOI18N

        editDishesMainSplitPane.setDividerLocation(400);
        editDishesMainSplitPane.setName("editDishesMainSplitPane"); // NOI18N

        dishEditDishListJPanel.setName("dishEditDishListJPanel"); // NOI18N

        allActiveDishesDishTableScrollPane.setName("allActiveDishesDishTableScrollPane"); // NOI18N

        allActiveDishesTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        allActiveDishesTable.setAutoCreateRowSorter(true);
        allActiveDishesTable.setModel(new DefaultTableModel());
        allActiveDishesTable.setName("allActiveDishesTable"); // NOI18N
        allActiveDishesDishTableScrollPane.setViewportView(allActiveDishesTable);

        searchDishSearchButton.setText(resourceMap.getString("searchDishSearchButton.text")); // NOI18N
        searchDishSearchButton.setName("searchDishSearchButton"); // NOI18N

        searchDishTextBox.setText(resourceMap.getString("searchDishTextBox.text")); // NOI18N
        searchDishTextBox.setName("searchDishTextBox"); // NOI18N

        addNewDishButton.setText(resourceMap.getString("addNewDishButton.text")); // NOI18N
        addNewDishButton.setName("addNewDishButton"); // NOI18N

        javax.swing.GroupLayout dishEditDishListJPanelLayout = new javax.swing.GroupLayout(dishEditDishListJPanel);
        dishEditDishListJPanel.setLayout(dishEditDishListJPanelLayout);
        dishEditDishListJPanelLayout.setHorizontalGroup(
            dishEditDishListJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishEditDishListJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewDishButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(searchDishTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchDishSearchButton)
                .addContainerGap())
            .addComponent(allActiveDishesDishTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        dishEditDishListJPanelLayout.setVerticalGroup(
            dishEditDishListJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishEditDishListJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishEditDishListJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewDishButton)
                    .addComponent(searchDishSearchButton)
                    .addComponent(searchDishTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allActiveDishesDishTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        editDishesMainSplitPane.setLeftComponent(dishEditDishListJPanel);

        editDishScrollPane.setName("editDishScrollPane"); // NOI18N

        editDishJPanel.setName("editDishJPanel"); // NOI18N

        dishEditNameLabel.setText(resourceMap.getString("dishEditNameLabel.text")); // NOI18N
        dishEditNameLabel.setName("dishEditNameLabel"); // NOI18N

        editDishNameTextBox.setText(resourceMap.getString("editDishNameTextBox.text")); // NOI18N
        editDishNameTextBox.setName("editDishNameTextBox"); // NOI18N

        dishEditDescriptionLabel.setText(resourceMap.getString("dishEditDescriptionLabel.text")); // NOI18N
        dishEditDescriptionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dishEditDescriptionLabel.setName("dishEditDescriptionLabel"); // NOI18N

        editDishDescriptionScrollPane.setName("editDishDescriptionScrollPane"); // NOI18N

        editDishDescriptionTextArea.setText(resourceMap.getString("editDishDescriptionTextArea.text")); // NOI18N
        editDishDescriptionTextArea.setName("editDishDescriptionTextArea"); // NOI18N
        editDishDescriptionScrollPane.setViewportView(editDishDescriptionTextArea);

        dishEditPriceLabel.setText(resourceMap.getString("dishEditPriceLabel.text")); // NOI18N
        dishEditPriceLabel.setName("dishEditPriceLabel"); // NOI18N

        dishIsVegetarianLabel.setText(resourceMap.getString("dishIsVegetarianLabel.text")); // NOI18N
        dishIsVegetarianLabel.setName("dishIsVegetarianLabel"); // NOI18N

        editDishIsVegetarianComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsVegetarianComboBox.setName("editDishIsVegetarianComboBox"); // NOI18N

        dishEditIsPSpicyLabel.setText(resourceMap.getString("dishEditIsPSpicyLabel.text")); // NOI18N
        dishEditIsPSpicyLabel.setName("dishEditIsPSpicyLabel"); // NOI18N

        editDishIsPsicyComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsPsicyComboBox.setName("editDishIsPsicyComboBox"); // NOI18N

        editDIshContainsNutsComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDIshContainsNutsComboBox.setName("editDIshContainsNutsComboBox"); // NOI18N

        dishEditContainsNutsLabel.setText(resourceMap.getString("dishEditContainsNutsLabel.text")); // NOI18N
        dishEditContainsNutsLabel.setName("dishEditContainsNutsLabel"); // NOI18N

        editDishContainsDairyComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishContainsDairyComboBox.setName("editDishContainsDairyComboBox"); // NOI18N

        dishEditContainsDairyLabel.setText(resourceMap.getString("dishEditContainsDairyLabel.text")); // NOI18N
        dishEditContainsDairyLabel.setName("dishEditContainsDairyLabel"); // NOI18N

        editDIshContainsGlutenComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDIshContainsGlutenComboBox.setName("editDIshContainsGlutenComboBox"); // NOI18N

        dishEditContainsGlutenLabel.setText(resourceMap.getString("dishEditContainsGlutenLabel.text")); // NOI18N
        dishEditContainsGlutenLabel.setName("dishEditContainsGlutenLabel"); // NOI18N

        dishEditIsActiveLabel.setText(resourceMap.getString("dishEditIsActiveLabel.text")); // NOI18N
        dishEditIsActiveLabel.setName("dishEditIsActiveLabel"); // NOI18N

        editDishIsDishActiveComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsDishActiveComboBox.setName("editDishIsDishActiveComboBox"); // NOI18N

        confirmDishEditButton.setText(resourceMap.getString("confirmDishEditButton.text")); // NOI18N
        confirmDishEditButton.setName("confirmDishEditButton"); // NOI18N

        editDishDishPriceTextArea.setText(resourceMap.getString("editDishDishPriceTextArea.text")); // NOI18N
        editDishDishPriceTextArea.setName("editDishDishPriceTextArea"); // NOI18N

        javax.swing.GroupLayout editDishJPanelLayout = new javax.swing.GroupLayout(editDishJPanel);
        editDishJPanel.setLayout(editDishJPanelLayout);
        editDishJPanelLayout.setHorizontalGroup(
            editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDishJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmDishEditButton)
                    .addGroup(editDishJPanelLayout.createSequentialGroup()
                        .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(editDishJPanelLayout.createSequentialGroup()
                                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dishEditPriceLabel)
                                    .addComponent(dishIsVegetarianLabel)
                                    .addComponent(dishEditIsPSpicyLabel)
                                    .addComponent(dishEditContainsNutsLabel)
                                    .addComponent(dishEditContainsDairyLabel)
                                    .addComponent(dishEditContainsGlutenLabel)
                                    .addComponent(dishEditIsActiveLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(dishEditDescriptionLabel)
                            .addGroup(editDishJPanelLayout.createSequentialGroup()
                                .addComponent(dishEditNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDishNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(editDishDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(editDishDishPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishIsDishActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishIsPsicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishIsVegetarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDIshContainsNutsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishContainsDairyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDIshContainsGlutenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        editDishJPanelLayout.setVerticalGroup(
            editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDishJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDishDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishDishPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsVegetarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishIsVegetarianLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsPsicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditIsPSpicyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDIshContainsNutsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsNutsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishContainsDairyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsDairyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDIshContainsGlutenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsGlutenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsDishActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditIsActiveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmDishEditButton)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        editDishScrollPane.setViewportView(editDishJPanel);

        editDishesMainSplitPane.setRightComponent(editDishScrollPane);

        javax.swing.GroupLayout DishEditingPanelLayout = new javax.swing.GroupLayout(DishEditingPanel);
        DishEditingPanel.setLayout(DishEditingPanelLayout);
        DishEditingPanelLayout.setHorizontalGroup(
            DishEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editDishesMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        DishEditingPanelLayout.setVerticalGroup(
            DishEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editDishesMainSplitPane)
        );

        mainTabbedPane.addTab(resourceMap.getString("DishEditingPanel.TabConstraints.tabTitle"), DishEditingPanel); // NOI18N

        ExtrasEditingPanel.setName("ExtrasEditingPanel"); // NOI18N

        extrasMainSplitPane.setDividerLocation(400);
        extrasMainSplitPane.setName("extrasMainSplitPane"); // NOI18N

        editExtraJPanel.setName("editExtraJPanel"); // NOI18N

        extraEditNameLabel.setText(resourceMap.getString("extraEditNameLabel.text")); // NOI18N
        extraEditNameLabel.setName("extraEditNameLabel"); // NOI18N

        editExtraExtraNameTextBox.setName("editExtraExtraNameTextBox"); // NOI18N

        extraEditPriceTextBox.setText(resourceMap.getString("extraEditPriceTextBox.text")); // NOI18N
        extraEditPriceTextBox.setName("extraEditPriceTextBox"); // NOI18N

        editExtraIsActiveLabel.setText(resourceMap.getString("editExtraIsActiveLabel.text")); // NOI18N
        editExtraIsActiveLabel.setName("editExtraIsActiveLabel"); // NOI18N

        editExtraExtraIsActiveComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editExtraExtraIsActiveComboBox.setName("editExtraExtraIsActiveComboBox"); // NOI18N

        confirmEditExtraButton.setText(resourceMap.getString("confirmEditExtraButton.text")); // NOI18N
        confirmEditExtraButton.setName("confirmEditExtraButton"); // NOI18N

        editExtraExtraPriceTextArea.setText(resourceMap.getString("editExtraExtraPriceTextArea.text")); // NOI18N
        editExtraExtraPriceTextArea.setName("editExtraExtraPriceTextArea"); // NOI18N

        javax.swing.GroupLayout editExtraJPanelLayout = new javax.swing.GroupLayout(editExtraJPanel);
        editExtraJPanel.setLayout(editExtraJPanelLayout);
        editExtraJPanelLayout.setHorizontalGroup(
            editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmEditExtraButton)
                    .addGroup(editExtraJPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(extraEditNameLabel)
                            .addGroup(editExtraJPanelLayout.createSequentialGroup()
                                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(extraEditPriceTextBox)
                                    .addComponent(editExtraIsActiveLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editExtraExtraNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(editExtraExtraPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editExtraExtraIsActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        editExtraJPanelLayout.setVerticalGroup(
            editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraExtraNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extraEditNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraExtraPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extraEditPriceTextBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraExtraIsActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editExtraIsActiveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmEditExtraButton)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        extrasMainSplitPane.setRightComponent(editExtraJPanel);

        editExtraExtraSelectionJPanel.setName("editExtraExtraSelectionJPanel"); // NOI18N

        allRegisteredExtrasScrollPane.setName("allRegisteredExtrasScrollPane"); // NOI18N

        allRegisteredExtrasTable.setAutoCreateRowSorter(true);
        allRegisteredExtrasTable.setModel(new DefaultTableModel());
        allRegisteredExtrasTable.setName("allRegisteredExtrasTable"); // NOI18N
        allRegisteredExtrasScrollPane.setViewportView(allRegisteredExtrasTable);

        searchExtraSearchButton.setText(resourceMap.getString("searchExtraSearchButton.text")); // NOI18N
        searchExtraSearchButton.setName("searchExtraSearchButton"); // NOI18N

        searchExtraTextBox.setName("searchExtraTextBox"); // NOI18N

        createNewExtraButton.setText(resourceMap.getString("createNewExtraButton.text")); // NOI18N
        createNewExtraButton.setName("createNewExtraButton"); // NOI18N

        javax.swing.GroupLayout editExtraExtraSelectionJPanelLayout = new javax.swing.GroupLayout(editExtraExtraSelectionJPanel);
        editExtraExtraSelectionJPanel.setLayout(editExtraExtraSelectionJPanelLayout);
        editExtraExtraSelectionJPanelLayout.setHorizontalGroup(
            editExtraExtraSelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editExtraExtraSelectionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewExtraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(searchExtraTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchExtraSearchButton)
                .addContainerGap())
            .addComponent(allRegisteredExtrasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        editExtraExtraSelectionJPanelLayout.setVerticalGroup(
            editExtraExtraSelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraExtraSelectionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editExtraExtraSelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewExtraButton)
                    .addComponent(searchExtraSearchButton)
                    .addComponent(searchExtraTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allRegisteredExtrasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        extrasMainSplitPane.setLeftComponent(editExtraExtraSelectionJPanel);

        javax.swing.GroupLayout ExtrasEditingPanelLayout = new javax.swing.GroupLayout(ExtrasEditingPanel);
        ExtrasEditingPanel.setLayout(ExtrasEditingPanelLayout);
        ExtrasEditingPanelLayout.setHorizontalGroup(
            ExtrasEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extrasMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        ExtrasEditingPanelLayout.setVerticalGroup(
            ExtrasEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extrasMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("ExtrasEditingPanel.TabConstraints.tabTitle"), ExtrasEditingPanel); // NOI18N

        settingsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        settingsScrollPane.setName("settingsScrollPane"); // NOI18N

        editSettingsJPanel.setName("editSettingsJPanel"); // NOI18N

        editSettingsNameOfRestaurantLabel.setText(resourceMap.getString("editSettingsNameOfRestaurantLabel.text")); // NOI18N
        editSettingsNameOfRestaurantLabel.setName("editSettingsNameOfRestaurantLabel"); // NOI18N

        settingsEditNameOfRestaurantTextBox.setText(resourceMap.getString("settingsEditNameOfRestaurantTextBox.text")); // NOI18N
        settingsEditNameOfRestaurantTextBox.setName("settingsEditNameOfRestaurantTextBox"); // NOI18N

        editSettingsMinimumOrderPriceLabel.setText(resourceMap.getString("editSettingsMinimumOrderPriceLabel.text")); // NOI18N
        editSettingsMinimumOrderPriceLabel.setName("editSettingsMinimumOrderPriceLabel"); // NOI18N

        settingsEditMinimumPriceFreeDeliveryTextBox.setText(resourceMap.getString("settingsEditMinimumPriceFreeDeliveryTextBox.text")); // NOI18N
        settingsEditMinimumPriceFreeDeliveryTextBox.setName("settingsEditMinimumPriceFreeDeliveryTextBox"); // NOI18N

        editSettingsDeliveryPriceLabel.setText(resourceMap.getString("editSettingsDeliveryPriceLabel.text")); // NOI18N
        editSettingsDeliveryPriceLabel.setName("editSettingsDeliveryPriceLabel"); // NOI18N

        settingsDeliveryPriceTextBox.setText(resourceMap.getString("settingsDeliveryPriceTextBox.text")); // NOI18N
        settingsDeliveryPriceTextBox.setName("settingsDeliveryPriceTextBox"); // NOI18N

        settingsApplyChangesButton.setText(resourceMap.getString("settingsApplyChangesButton.text")); // NOI18N
        settingsApplyChangesButton.setName("settingsApplyChangesButton"); // NOI18N

        settingsResetSettingsButton.setText(resourceMap.getString("settingsResetSettingsButton.text")); // NOI18N
        settingsResetSettingsButton.setName("settingsResetSettingsButton"); // NOI18N

        javax.swing.GroupLayout editSettingsJPanelLayout = new javax.swing.GroupLayout(editSettingsJPanel);
        editSettingsJPanel.setLayout(editSettingsJPanelLayout);
        editSettingsJPanelLayout.setHorizontalGroup(
            editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editSettingsNameOfRestaurantLabel)
                    .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                        .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editSettingsDeliveryPriceLabel)
                            .addComponent(editSettingsMinimumOrderPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                        .addComponent(settingsApplyChangesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(settingsResetSettingsButton))
                    .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(settingsDeliveryPriceTextBox)
                        .addComponent(settingsEditMinimumPriceFreeDeliveryTextBox)
                        .addComponent(settingsEditNameOfRestaurantTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        editSettingsJPanelLayout.setVerticalGroup(
            editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsEditNameOfRestaurantTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSettingsNameOfRestaurantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSettingsMinimumOrderPriceLabel)
                    .addComponent(settingsEditMinimumPriceFreeDeliveryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsDeliveryPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSettingsDeliveryPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsApplyChangesButton)
                    .addComponent(settingsResetSettingsButton))
                .addContainerGap(410, Short.MAX_VALUE))
        );

        settingsScrollPane.setViewportView(editSettingsJPanel);

        mainTabbedPane.addTab(resourceMap.getString("settingsScrollPane.TabConstraints.tabTitle"), settingsScrollPane); // NOI18N

        add(mainTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel CustomerEditingJPanel;
    public static javax.swing.JPanel DishEditingPanel;
    public static javax.swing.JPanel ExtrasEditingPanel;
    public static javax.swing.JButton addNewCustomerButton;
    public static javax.swing.JButton addNewDishButton;
    public static javax.swing.JTable allActiveCustomersTable;
    public static javax.swing.JScrollPane allActiveDishesDishTableScrollPane;
    public static javax.swing.JTable allActiveDishesTable;
    public static javax.swing.JScrollPane allCustomersTableScrollPane;
    public static javax.swing.JScrollPane allRegisteredExtrasScrollPane;
    public static javax.swing.JTable allRegisteredExtrasTable;
    public static javax.swing.JButton confirmDishEditButton;
    public static javax.swing.JButton confirmEditExtraButton;
    public static javax.swing.JButton createNewExtraButton;
    public static javax.swing.JTextField customerEditAddressTextBox;
    public static javax.swing.JTextField customerEditCityTextBox;
    public static javax.swing.JTextArea customerEditCommentsTextArea;
    public static javax.swing.JButton customerEditConfirmChangesButton;
    public static javax.swing.JPanel customerEditCustomerListPanel;
    public static javax.swing.JButton customerEditDeleteSelectedCustomerButton;
    public static javax.swing.JTextField customerEditFirstNameTextBox;
    public static javax.swing.JTextField customerEditLastNameTextBox;
    public static javax.swing.JTextField customerEditPhoneNumberTextBox;
    public static javax.swing.JTextField customerEditPostalCodeTextBox;
    public static javax.swing.JButton customerEditResetChangesButton;
    public static javax.swing.JLabel dishEditContainsDairyLabel;
    public static javax.swing.JLabel dishEditContainsGlutenLabel;
    public static javax.swing.JLabel dishEditContainsNutsLabel;
    public static javax.swing.JLabel dishEditDescriptionLabel;
    public static javax.swing.JPanel dishEditDishListJPanel;
    public static javax.swing.JLabel dishEditIsActiveLabel;
    public static javax.swing.JLabel dishEditIsPSpicyLabel;
    public static javax.swing.JLabel dishEditNameLabel;
    public static javax.swing.JLabel dishEditPriceLabel;
    public static javax.swing.JLabel dishIsVegetarianLabel;
    public static javax.swing.JLabel editCustomerAddressLabel;
    public static javax.swing.JLabel editCustomerCityLabel;
    public static javax.swing.JLabel editCustomerCommentsLabel;
    public static javax.swing.JScrollPane editCustomerCommentsTextAreaScrollPane;
    public static javax.swing.JPanel editCustomerEditPanel;
    public static javax.swing.JScrollPane editCustomerEditScrollPane;
    public static javax.swing.JLabel editCustomerFirstNameLabel;
    public static javax.swing.JLabel editCustomerLastNameLabel;
    public static javax.swing.JSplitPane editCustomerMainSplitPane;
    public static javax.swing.JLabel editCustomerPhoneNumberLabel;
    public static javax.swing.JLabel editCustomerPostalCodeLabel;
    public static javax.swing.JComboBox editDIshContainsGlutenComboBox;
    public static javax.swing.JComboBox editDIshContainsNutsComboBox;
    public static javax.swing.JComboBox editDishContainsDairyComboBox;
    public static javax.swing.JScrollPane editDishDescriptionScrollPane;
    public static javax.swing.JTextPane editDishDescriptionTextArea;
    public static javax.swing.JTextField editDishDishPriceTextArea;
    public static javax.swing.JComboBox editDishIsDishActiveComboBox;
    public static javax.swing.JComboBox editDishIsPsicyComboBox;
    public static javax.swing.JComboBox editDishIsVegetarianComboBox;
    public static javax.swing.JPanel editDishJPanel;
    public static javax.swing.JTextField editDishNameTextBox;
    public static javax.swing.JScrollPane editDishScrollPane;
    public static javax.swing.JSplitPane editDishesMainSplitPane;
    public static javax.swing.JComboBox editExtraExtraIsActiveComboBox;
    public static javax.swing.JTextField editExtraExtraNameTextBox;
    public static javax.swing.JTextField editExtraExtraPriceTextArea;
    public static javax.swing.JPanel editExtraExtraSelectionJPanel;
    public static javax.swing.JLabel editExtraIsActiveLabel;
    public static javax.swing.JPanel editExtraJPanel;
    public static javax.swing.JLabel editSettingsDeliveryPriceLabel;
    public static javax.swing.JPanel editSettingsJPanel;
    public static javax.swing.JLabel editSettingsMinimumOrderPriceLabel;
    public static javax.swing.JLabel editSettingsNameOfRestaurantLabel;
    public static javax.swing.JLabel extraEditNameLabel;
    public static javax.swing.JLabel extraEditPriceTextBox;
    public static javax.swing.JSplitPane extrasMainSplitPane;
    public static javax.swing.JTabbedPane mainTabbedPane;
    public static javax.swing.JButton searchCustomerButton;
    public static javax.swing.JTextField searchCustomerTextBox;
    public static javax.swing.JButton searchDishSearchButton;
    public static javax.swing.JTextField searchDishTextBox;
    public static javax.swing.JButton searchExtraSearchButton;
    public static javax.swing.JTextField searchExtraTextBox;
    public static javax.swing.JButton settingsApplyChangesButton;
    public static javax.swing.JTextField settingsDeliveryPriceTextBox;
    public static javax.swing.JTextField settingsEditMinimumPriceFreeDeliveryTextBox;
    public static javax.swing.JTextField settingsEditNameOfRestaurantTextBox;
    public static javax.swing.JButton settingsResetSettingsButton;
    public static javax.swing.JScrollPane settingsScrollPane;
    // End of variables declaration//GEN-END:variables
}
