/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CookView.java
 *
 * Created on 09.okt.2011, 14:27:40
 */
package pizzaprogram.gui.views;

/**
 *
 * @author Bart
 */
public class CookView extends javax.swing.JPanel {

    /** Creates new form CookView */
    public CookView() {
        initComponents();
    }
    
    public String toString()
    {
        return "CookView";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainSplitPane.setDividerLocation(250);
        mainSplitPane.setName("mainSplitPane"); // NOI18N

        orderEditSplitPane.setDividerLocation(300);
        orderEditSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        orderEditSplitPane.setName("orderEditSplitPane"); // NOI18N

        currentOrderTableScrollPane.setName("currentOrderTableScrollPane"); // NOI18N

        currentOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dish", "Extra", "In progress", "Finished"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        currentOrderTable.setName("currentOrderTable"); // NOI18N
        currentOrderTableScrollPane.setViewportView(currentOrderTable);

        orderEditSplitPane.setLeftComponent(currentOrderTableScrollPane);

        generalOrderPropertiesPane.setName("generalOrderPropertiesPane"); // NOI18N

        orderCommentsFieldScrollPane.setName("orderCommentsFieldScrollPane"); // NOI18N

        orderCommentsTextArea.setColumns(20);
        orderCommentsTextArea.setLineWrap(true);
        orderCommentsTextArea.setRows(3);
        orderCommentsTextArea.setName("orderCommentsTextArea"); // NOI18N
        orderCommentsFieldScrollPane.setViewportView(orderCommentsTextArea);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getResourceMap(CookView.class);
        orderCommentsLabel.setText(resourceMap.getString("orderCommentsLabel.text")); // NOI18N
        orderCommentsLabel.setName("orderCommentsLabel"); // NOI18N

        confirmOrderButton.setText(resourceMap.getString("confirmOrderButton.text")); // NOI18N
        confirmOrderButton.setName("confirmOrderButton"); // NOI18N

        javax.swing.GroupLayout generalOrderPropertiesPaneLayout = new javax.swing.GroupLayout(generalOrderPropertiesPane);
        generalOrderPropertiesPane.setLayout(generalOrderPropertiesPaneLayout);
        generalOrderPropertiesPaneLayout.setHorizontalGroup(
            generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalOrderPropertiesPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderCommentsFieldScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(orderCommentsLabel)
                    .addComponent(confirmOrderButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        generalOrderPropertiesPaneLayout.setVerticalGroup(
            generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalOrderPropertiesPaneLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(orderCommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsFieldScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmOrderButton)
                .addContainerGap())
        );

        orderEditSplitPane.setRightComponent(generalOrderPropertiesPane);

        mainSplitPane.setRightComponent(orderEditSplitPane);

        orderSelectionPanel.setName("orderSelectionPanel"); // NOI18N

        searchOrderButton.setText(resourceMap.getString("searchOrderButton.text")); // NOI18N
        searchOrderButton.setName("searchOrderButton"); // NOI18N

        ordersTableScrollPane.setName("ordersTableScrollPane"); // NOI18N

        orderDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order", "Status", "Time registered"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailsTable.setName("orderDetailsTable"); // NOI18N
        ordersTableScrollPane.setViewportView(orderDetailsTable);

        orderSearchTextPane.setName("orderSearchTextPane"); // NOI18N

        javax.swing.GroupLayout orderSelectionPanelLayout = new javax.swing.GroupLayout(orderSelectionPanel);
        orderSelectionPanel.setLayout(orderSelectionPanelLayout);
        orderSelectionPanelLayout.setHorizontalGroup(
            orderSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderSearchTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(searchOrderButton)
                .addGap(10, 10, 10))
            .addComponent(ordersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        orderSelectionPanelLayout.setVerticalGroup(
            orderSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchOrderButton)
                    .addComponent(orderSearchTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        mainSplitPane.setLeftComponent(orderSelectionPanel);

        add(mainSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JButton confirmOrderButton = new javax.swing.JButton();
    public static final javax.swing.JTable currentOrderTable = new javax.swing.JTable();
    public static final javax.swing.JScrollPane currentOrderTableScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel generalOrderPropertiesPane = new javax.swing.JPanel();
    public static final javax.swing.JSplitPane mainSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JScrollPane orderCommentsFieldScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JLabel orderCommentsLabel = new javax.swing.JLabel();
    public static final javax.swing.JTextArea orderCommentsTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JTable orderDetailsTable = new javax.swing.JTable();
    public static final javax.swing.JSplitPane orderEditSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JTextPane orderSearchTextPane = new javax.swing.JTextPane();
    public static final javax.swing.JPanel orderSelectionPanel = new javax.swing.JPanel();
    public static final javax.swing.JScrollPane ordersTableScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JButton searchOrderButton = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
