/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

/*
* CookView.java
*
* Created on 09.okt.2011, 14:27:40
*/
package pizzaprogram.gui.views;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
*
* @author Bart
*/
public class CookView extends javax.swing.JPanel {

    /** Creates new form CookView */
    public CookView() {
        initComponents();
    }
    
    public String toString()
    {
        return "CookView";
    }

    /** This method is called from within the constructor to
* initialize the form.
* WARNING: Do NOT modify this code. The content of this method is
* always regenerated by the Form Editor.
*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainSplitPane.setDividerLocation(250);
        mainSplitPane.setName("mainSplitPane"); // NOI18N

        orderEditSplitPane.setDividerLocation(350);
        orderEditSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        orderEditSplitPane.setName("orderEditSplitPane"); // NOI18N

        currentOrderTableScrollPane.setName("currentOrderTableScrollPane"); // NOI18N

        currentOrderTable.setAutoCreateRowSorter(true);
        currentOrderTable.setModel(new DefaultTableModel());
        currentOrderTable.setName("currentOrderTable"); // NOI18N
        currentOrderTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        currentOrderTableScrollPane.setViewportView(currentOrderTable);

        orderEditSplitPane.setLeftComponent(currentOrderTableScrollPane);

        generalOrderPropertiesPane.setName("generalOrderPropertiesPane"); // NOI18N

        orderCommentsFieldScrollPane.setName("orderCommentsFieldScrollPane"); // NOI18N

        orderCommentsTextArea.setColumns(20);
        orderCommentsTextArea.setEditable(false);
        orderCommentsTextArea.setLineWrap(true);
        orderCommentsTextArea.setRows(3);
        orderCommentsTextArea.setName("orderCommentsTextArea"); // NOI18N
        orderCommentsFieldScrollPane.setViewportView(orderCommentsTextArea);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getResourceMap(CookView.class);
        orderCommentsLabel.setText(resourceMap.getString("orderCommentsLabel.text")); // NOI18N
        orderCommentsLabel.setName("orderCommentsLabel"); // NOI18N

        markOrderCompletedButton.setText(resourceMap.getString("markOrderCompletedButton.text")); // NOI18N
        markOrderCompletedButton.setName("markOrderCompletedButton"); // NOI18N

        markOrderInProgressButton.setText(resourceMap.getString("markOrderInProgressButton.text")); // NOI18N
        markOrderInProgressButton.setName("markOrderInProgressButton"); // NOI18N

        javax.swing.GroupLayout generalOrderPropertiesPaneLayout = new javax.swing.GroupLayout(generalOrderPropertiesPane);
        generalOrderPropertiesPane.setLayout(generalOrderPropertiesPaneLayout);
        generalOrderPropertiesPaneLayout.setHorizontalGroup(
            generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalOrderPropertiesPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderCommentsFieldScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(orderCommentsLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalOrderPropertiesPaneLayout.createSequentialGroup()
                        .addComponent(markOrderInProgressButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markOrderCompletedButton)))
                .addContainerGap())
        );
        generalOrderPropertiesPaneLayout.setVerticalGroup(
            generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalOrderPropertiesPaneLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(orderCommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsFieldScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalOrderPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markOrderCompletedButton)
                    .addComponent(markOrderInProgressButton))
                .addContainerGap())
        );

        orderEditSplitPane.setRightComponent(generalOrderPropertiesPane);

        mainSplitPane.setRightComponent(orderEditSplitPane);

        orderSelectionPanel.setName("orderSelectionPanel"); // NOI18N

        ordersTableScrollPane.setName("ordersTableScrollPane"); // NOI18N

        orderDetailsTable.setAutoCreateRowSorter(true);
        orderDetailsTable.setModel(new DefaultTableModel());
        orderDetailsTable.setName("orderDetailsTable"); // NOI18N
        orderDetailsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ordersTableScrollPane.setViewportView(orderDetailsTable);

        orderSearchTextPane.setText(resourceMap.getString("orderSearchTextPane.text")); // NOI18N
        orderSearchTextPane.setName("orderSearchTextPane"); // NOI18N

        javax.swing.GroupLayout orderSelectionPanelLayout = new javax.swing.GroupLayout(orderSelectionPanel);
        orderSelectionPanel.setLayout(orderSelectionPanelLayout);
        orderSelectionPanelLayout.setHorizontalGroup(
            orderSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
            .addGroup(orderSelectionPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(orderSearchTextPane, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
        );
        orderSelectionPanelLayout.setVerticalGroup(
            orderSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSelectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderSearchTextPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );

        mainSplitPane.setLeftComponent(orderSelectionPanel);

        add(mainSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTable currentOrderTable = new javax.swing.JTable(){
        public boolean isCellEditable(int rowIndex, int colIndex) {
            return false; //Disallow the editing of any cell
        }
    };
    public static final javax.swing.JScrollPane currentOrderTableScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel generalOrderPropertiesPane = new javax.swing.JPanel();
    public static final javax.swing.JSplitPane mainSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JButton markOrderCompletedButton = new javax.swing.JButton();
    public static final javax.swing.JButton markOrderInProgressButton = new javax.swing.JButton();
    public static final javax.swing.JScrollPane orderCommentsFieldScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JLabel orderCommentsLabel = new javax.swing.JLabel();
    public static final javax.swing.JTextArea orderCommentsTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JTable orderDetailsTable = new JTable(){
        public boolean isCellEditable(int rowIndex, int colIndex) {
            return false; //Disallow the editing of any cell
        }
    };
    public static final javax.swing.JSplitPane orderEditSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JTextField orderSearchTextPane = new javax.swing.JTextField();
    public static final javax.swing.JPanel orderSelectionPanel = new javax.swing.JPanel();
    public static final javax.swing.JScrollPane ordersTableScrollPane = new javax.swing.JScrollPane();
    // End of variables declaration//GEN-END:variables
}

