/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeliveryView.java
 *
 * Created on 09.okt.2011, 15:39:42
 */
package pizzaprogram.gui.views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bart
 */
public class DeliveryView extends javax.swing.JPanel {

    /** Creates new form DeliveryView */
    public DeliveryView() {
        initComponents();
    }
 public String toString()
    {
        return "DeliveryView";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainVerticalSplitPanel.setDividerLocation(300);
        mainVerticalSplitPanel.setName("mainVerticalSplitPanel"); // NOI18N

        rightHorizontallSplitPane.setDividerLocation(200);
        rightHorizontallSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        rightHorizontallSplitPane.setName("rightHorizontallSplitPane"); // NOI18N

        orderContentsPanel.setName("orderContentsPanel"); // NOI18N

        orderContentsTableScrollPane.setName("orderContentsTableScrollPane"); // NOI18N

        orderContentsTable.setAutoCreateRowSorter(true);
        orderContentsTable.setModel(new DefaultTableModel());
        orderContentsTable.setName("orderContentsTable"); // NOI18N
        orderContentsTable.getTableHeader().setReorderingAllowed(false);
        orderContentsTableScrollPane.setViewportView(orderContentsTable);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getResourceMap(DeliveryView.class);
        markOrderDeliveredButton.setText(resourceMap.getString("markOrderDeliveredButton.text")); // NOI18N
        markOrderDeliveredButton.setName("markOrderDeliveredButton"); // NOI18N

        showReceiptButton.setText(resourceMap.getString("showReceiptButton.text")); // NOI18N
        showReceiptButton.setName("showReceiptButton"); // NOI18N

        markOrderBeingDeliveredButton.setText(resourceMap.getString("markOrderBeingDeliveredButton.text")); // NOI18N
        markOrderBeingDeliveredButton.setName("markOrderBeingDeliveredButton"); // NOI18N

        javax.swing.GroupLayout orderContentsPanelLayout = new javax.swing.GroupLayout(orderContentsPanel);
        orderContentsPanel.setLayout(orderContentsPanelLayout);
        orderContentsPanelLayout.setHorizontalGroup(
            orderContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderContentsPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(showReceiptButton)
                .addGap(6, 6, 6)
                .addComponent(markOrderBeingDeliveredButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markOrderDeliveredButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        orderContentsPanelLayout.setVerticalGroup(
            orderContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderContentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showReceiptButton)
                    .addComponent(markOrderDeliveredButton)
                    .addComponent(markOrderBeingDeliveredButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        rightHorizontallSplitPane.setTopComponent(orderContentsPanel);

        mapImagePanel.setDoubleBuffered(false);
        mapImagePanel.setName("mapImagePanel"); // NOI18N
        mapImagePanel.setOpaque(false);

        javax.swing.GroupLayout mapImagePanelLayout = new javax.swing.GroupLayout(mapImagePanel);
        mapImagePanel.setLayout(mapImagePanelLayout);
        mapImagePanelLayout.setHorizontalGroup(
            mapImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        mapImagePanelLayout.setVerticalGroup(
            mapImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        rightHorizontallSplitPane.setRightComponent(mapImagePanel);

        mainVerticalSplitPanel.setRightComponent(rightHorizontallSplitPane);

        leftHorizontalSplitPanel.setDividerLocation(240);
        leftHorizontalSplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        leftHorizontalSplitPanel.setName("leftHorizontalSplitPanel"); // NOI18N

        activeOrderListPanel.setName("activeOrderListPanel"); // NOI18N

        orderSearchTextField.setName("orderSearchTextField"); // NOI18N

        orderSearchButton.setText(resourceMap.getString("orderSearchButton.text")); // NOI18N
        orderSearchButton.setName("orderSearchButton"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        activeOrdersTable.setAutoCreateRowSorter(true);
        activeOrdersTable.setModel(new DefaultTableModel());
        activeOrdersTable.setName("activeOrdersTable"); // NOI18N
        jScrollPane1.setViewportView(activeOrdersTable);
        activeOrdersTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("activeOrdersTable.columnModel.title0")); // NOI18N
        activeOrdersTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("activeOrdersTable.columnModel.title1")); // NOI18N
        activeOrdersTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("activeOrdersTable.columnModel.title2")); // NOI18N
        activeOrdersTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("activeOrdersTable.columnModel.title3")); // NOI18N

        javax.swing.GroupLayout activeOrderListPanelLayout = new javax.swing.GroupLayout(activeOrderListPanel);
        activeOrderListPanel.setLayout(activeOrderListPanelLayout);
        activeOrderListPanelLayout.setHorizontalGroup(
            activeOrderListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeOrderListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderSearchButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        activeOrderListPanelLayout.setVerticalGroup(
            activeOrderListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(activeOrderListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(activeOrderListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderSearchButton)
                    .addComponent(orderSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        leftHorizontalSplitPanel.setTopComponent(activeOrderListPanel);

        orderDetailsPanel.setName("orderDetailsPanel"); // NOI18N

        orderCommentsScrollPane.setName("orderCommentsScrollPane"); // NOI18N

        orderCommentsTextArea.setColumns(20);
        orderCommentsTextArea.setEditable(false);
        orderCommentsTextArea.setLineWrap(true);
        orderCommentsTextArea.setRows(3);
        orderCommentsTextArea.setFocusable(false);
        orderCommentsTextArea.setName("orderCommentsTextArea"); // NOI18N
        orderCommentsScrollPane.setViewportView(orderCommentsTextArea);

        orderCommentsLabel.setText(resourceMap.getString("orderCommentsLabel.text")); // NOI18N
        orderCommentsLabel.setName("orderCommentsLabel"); // NOI18N

        orderAddressScrollPane.setName("orderAddressScrollPane"); // NOI18N

        orderAddressTextArea.setColumns(20);
        orderAddressTextArea.setEditable(false);
        orderAddressTextArea.setLineWrap(true);
        orderAddressTextArea.setRows(3);
        orderAddressTextArea.setFocusable(false);
        orderAddressTextArea.setName("orderAddressTextArea"); // NOI18N
        orderAddressScrollPane.setViewportView(orderAddressTextArea);

        orderAddressLabel.setText(resourceMap.getString("orderAddressLabel.text")); // NOI18N
        orderAddressLabel.setName("orderAddressLabel"); // NOI18N

        orderDetailsSeparator.setName("orderDetailsSeparator"); // NOI18N

        orderPriceOverviewPanel.setName("orderPriceOverviewPanel"); // NOI18N

        orderCostOrderPriceLabel.setText(resourceMap.getString("orderCostOrderPriceLabel.text")); // NOI18N
        orderCostOrderPriceLabel.setName("orderCostOrderPriceLabel"); // NOI18N

        orderCostDeliveryCostLabel.setText(resourceMap.getString("orderCostDeliveryCostLabel.text")); // NOI18N
        orderCostDeliveryCostLabel.setName("orderCostDeliveryCostLabel"); // NOI18N

        orderCostTotalCostLabel.setText(resourceMap.getString("orderCostTotalCostLabel.text")); // NOI18N
        orderCostTotalCostLabel.setName("orderCostTotalCostLabel"); // NOI18N

        orderCostOrderPrice.setText(resourceMap.getString("orderCostOrderPrice.text")); // NOI18N
        orderCostOrderPrice.setName("orderCostOrderPrice"); // NOI18N

        orderCostDeliveryCost.setText(resourceMap.getString("orderCostDeliveryCost.text")); // NOI18N
        orderCostDeliveryCost.setName("orderCostDeliveryCost"); // NOI18N

        orderCostTotalCost.setText(resourceMap.getString("orderCostTotalCost.text")); // NOI18N
        orderCostTotalCost.setName("orderCostTotalCost"); // NOI18N

        javax.swing.GroupLayout orderPriceOverviewPanelLayout = new javax.swing.GroupLayout(orderPriceOverviewPanel);
        orderPriceOverviewPanel.setLayout(orderPriceOverviewPanelLayout);
        orderPriceOverviewPanelLayout.setHorizontalGroup(
            orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPriceOverviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPriceOverviewPanelLayout.createSequentialGroup()
                        .addComponent(orderCostOrderPriceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(orderCostOrderPrice))
                    .addGroup(orderPriceOverviewPanelLayout.createSequentialGroup()
                        .addGroup(orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderCostDeliveryCostLabel)
                            .addComponent(orderCostTotalCostLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderCostTotalCost)
                            .addComponent(orderCostDeliveryCost))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        orderPriceOverviewPanelLayout.setVerticalGroup(
            orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPriceOverviewPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCostOrderPriceLabel)
                    .addComponent(orderCostOrderPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCostDeliveryCostLabel)
                    .addComponent(orderCostDeliveryCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPriceOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCostTotalCostLabel)
                    .addComponent(orderCostTotalCost)))
        );

        javax.swing.GroupLayout orderDetailsPanelLayout = new javax.swing.GroupLayout(orderDetailsPanel);
        orderDetailsPanel.setLayout(orderDetailsPanelLayout);
        orderDetailsPanelLayout.setHorizontalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                .addGroup(orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderDetailsSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderCommentsLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderCommentsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderAddressLabel))
                    .addGroup(orderDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(orderAddressScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                    .addComponent(orderPriceOverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        orderDetailsPanelLayout.setVerticalGroup(
            orderDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderDetailsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderPriceOverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderDetailsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderAddressLabel)
                .addGap(3, 3, 3)
                .addComponent(orderAddressScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        leftHorizontalSplitPanel.setRightComponent(orderDetailsPanel);

        mainVerticalSplitPanel.setLeftComponent(leftHorizontalSplitPanel);

        add(mainVerticalSplitPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JPanel activeOrderListPanel = new javax.swing.JPanel();
    public static final javax.swing.JTable activeOrdersTable = {
        public boolean isCellEditable(int rowIndex, int colIndex) {
            return false; //Disallow the editing of any cell
        }
    };
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public static final javax.swing.JSplitPane leftHorizontalSplitPanel = new javax.swing.JSplitPane();
    public static final javax.swing.JSplitPane mainVerticalSplitPanel = new javax.swing.JSplitPane();
    public static final javax.swing.JPanel mapImagePanel = new javax.swing.JPanel();
    public static final javax.swing.JButton markOrderBeingDeliveredButton = new javax.swing.JButton();
    public static final javax.swing.JButton markOrderDeliveredButton = new javax.swing.JButton();
    public static final javax.swing.JLabel orderAddressLabel = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane orderAddressScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTextArea orderAddressTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JLabel orderCommentsLabel = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane orderCommentsScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTextArea orderCommentsTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JPanel orderContentsPanel = new javax.swing.JPanel();
    public static final javax.swing.JTable orderContentsTable = new javax.swing.JTable();
    public static final javax.swing.JScrollPane orderContentsTableScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JLabel orderCostDeliveryCost = new javax.swing.JLabel();
    public static final javax.swing.JLabel orderCostDeliveryCostLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel orderCostOrderPrice = new javax.swing.JLabel();
    public static final javax.swing.JLabel orderCostOrderPriceLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel orderCostTotalCost = new javax.swing.JLabel();
    public static final javax.swing.JLabel orderCostTotalCostLabel = new javax.swing.JLabel();
    public static final javax.swing.JPanel orderDetailsPanel = new javax.swing.JPanel();
    public static final javax.swing.JSeparator orderDetailsSeparator = new javax.swing.JSeparator();
    public static final javax.swing.JPanel orderPriceOverviewPanel = new javax.swing.JPanel();
    public static final javax.swing.JButton orderSearchButton = new javax.swing.JButton();
    public static final javax.swing.JTextField orderSearchTextField = new javax.swing.JTextField();
    public static final javax.swing.JSplitPane rightHorizontallSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JButton showReceiptButton = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
