/*
 * DesktopApplication1View.java
 */

package pizzaprogram.gui;

import pizzaprogram.core.PizzaProgram;
import pizzaprogram.gui.views.DesktopApplication1AboutBox;
import java.awt.MenuBar;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenuBar;

/**
 * The application's main frame.
 */
public class ProgramWindowFrameView extends FrameView {

    public ProgramWindowFrameView(SingleFrameApplication app) {
        super(app);

        initComponents();

    }
    
    public JMenuBar getMenuBar()
    {
        return this.menuBar;
    }
    
    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = PizzaProgram.getApplication().getMainFrame();
            aboutBox = new DesktopApplication1AboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        PizzaProgram.getApplication().show(aboutBox);
    }

    public JMenuItem getOpenEditMenuWindowMenuItem() {
        return openEditMenuWindowMenuItem;
    }

    public JMenuItem getOpenSettingsWindowMenuItem() {
        return openSettingsWindowMenuItem;
    }

    public JMenuItem getRefreshDataMenuItem() {
        return refreshDataMenuItem;
    }

    public JRadioButtonMenuItem getShowCookGUIMenuItem() {
        return showCookGUIMenuItem;
    }

    public JRadioButtonMenuItem getShowDeliveryGUIMenuItem() {
        return showDeliveryGUIMenuItem;
    }

    public JRadioButtonMenuItem getShowOrderGUIMenuItem() {
        return showOrderGUIMenuItem;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        refreshDataMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        showOrderGUIMenuItem = new javax.swing.JRadioButtonMenuItem();
        showCookGUIMenuItem = new javax.swing.JRadioButtonMenuItem();
        showDeliveryGUIMenuItem = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        GUIMenuItemSelectionButtonGroup = new javax.swing.ButtonGroup();

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getResourceMap(ProgramWindowFrameView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getActionMap(ProgramWindowFrameView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText(resourceMap.getString("editMenu.text")); // NOI18N
        editMenu.setName("editMenu"); // NOI18N

        refreshDataMenuItem.setText(resourceMap.getString("refreshDataMenuItem.text")); // NOI18N
        refreshDataMenuItem.setName("refreshDataMenuItem"); // NOI18N
        editMenu.add(refreshDataMenuItem);

        menuBar.add(editMenu);

        jMenu2.setText(resourceMap.getString("jMenu2.text")); // NOI18N
        jMenu2.setName("jMenu2"); // NOI18N

        GUIMenuItemSelectionButtonGroup.add(showOrderGUIMenuItem);
        showOrderGUIMenuItem.setSelected(true);
        showOrderGUIMenuItem.setText(resourceMap.getString("showOrderGUIMenuItem.text")); // NOI18N
        showOrderGUIMenuItem.setName("showOrderGUIMenuItem"); // NOI18N
        jMenu2.add(showOrderGUIMenuItem);

        GUIMenuItemSelectionButtonGroup.add(showCookGUIMenuItem);
        showCookGUIMenuItem.setText(resourceMap.getString("showCookGUIMenuItem.text")); // NOI18N
        showCookGUIMenuItem.setName("showCookGUIMenuItem"); // NOI18N
        jMenu2.add(showCookGUIMenuItem);

        GUIMenuItemSelectionButtonGroup.add(showDeliveryGUIMenuItem);
        showDeliveryGUIMenuItem.setText(resourceMap.getString("showDeliveryGUIMenuItem.text")); // NOI18N
        showDeliveryGUIMenuItem.setName("showDeliveryGUIMenuItem"); // NOI18N
        jMenu2.add(showDeliveryGUIMenuItem);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText(resourceMap.getString("jRadioButtonMenuItem1.text")); // NOI18N
        jRadioButtonMenuItem1.setName("jRadioButtonMenuItem1"); // NOI18N
        jMenu2.add(jRadioButtonMenuItem1);

        menuBar.add(jMenu2);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GUIMenuItemSelectionButtonGroup;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem refreshDataMenuItem;
    private javax.swing.JRadioButtonMenuItem showCookGUIMenuItem;
    private javax.swing.JRadioButtonMenuItem showDeliveryGUIMenuItem;
    private javax.swing.JRadioButtonMenuItem showOrderGUIMenuItem;
    // End of variables declaration//GEN-END:variables


    private JDialog aboutBox;
}
