/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminView.java
 *
 * Created on 06.nov.2011, 13:44:26
 */
package pizzaProgram.gui.views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bart
 */
public class AdminView extends javax.swing.JPanel {

    /** Creates new form AdminView */
    public AdminView() {
        initComponents();
    }
    
    public String toString()
    {
        return "AdminView";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        DishEditingPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        dishEditNameLabel = new javax.swing.JLabel();
        editDishNameTextBox = new javax.swing.JTextField();
        dishEditDescriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editDishDescriptionTextArea = new javax.swing.JTextPane();
        editDishDishPriceTextArea = new javax.swing.JFormattedTextField();
        dishEditPriceLabel = new javax.swing.JLabel();
        dishIsVegetarianLabel = new javax.swing.JLabel();
        editDishIsVegetarianComboBox = new javax.swing.JComboBox();
        dishEditIsPSpicyLabel = new javax.swing.JLabel();
        editDishIsPsicyComboBox = new javax.swing.JComboBox();
        editDIshContainsNutsComboBox = new javax.swing.JComboBox();
        dishEditContainsNutsLabel = new javax.swing.JLabel();
        editDishContainsDairyComboBox = new javax.swing.JComboBox();
        dishEditContainsDairyLabel = new javax.swing.JLabel();
        editDIshContainsGlutenComboBox = new javax.swing.JComboBox();
        dishEditContainsGlutenLabel = new javax.swing.JLabel();
        dishEditIsActiveLabel = new javax.swing.JLabel();
        editDishIsDishActiveComboBox = new javax.swing.JComboBox();
        confirmDishEditButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allActiveDishesTable = new javax.swing.JTable();
        searchDishSearchButton = new javax.swing.JButton();
        searchDishTextBox = new javax.swing.JTextField();
        addNewDishButton = new javax.swing.JButton();
        ExtrasEditingPanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        editExtraExtraNameTextBox = new javax.swing.JTextField();
        editDishPriceTextBox = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        editExtraExtraIsActiveComboBox = new javax.swing.JComboBox();
        confirmEditExtraButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        allRegisteredExtrasTable = new javax.swing.JTable();
        searchExtraSearchButton = new javax.swing.JButton();
        searchExtraTextBox = new javax.swing.JTextField();
        createNewExtraButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainTabbedPane.setName("mainTabbedPane"); // NOI18N

        DishEditingPanel.setName("DishEditingPanel"); // NOI18N

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaProgram.core.PizzaProgram.class).getContext().getResourceMap(AdminView.class);
        dishEditNameLabel.setText(resourceMap.getString("dishEditNameLabel.text")); // NOI18N
        dishEditNameLabel.setName("dishEditNameLabel"); // NOI18N

        editDishNameTextBox.setText(resourceMap.getString("editDishNameTextBox.text")); // NOI18N
        editDishNameTextBox.setName("editDishNameTextBox"); // NOI18N

        dishEditDescriptionLabel.setText(resourceMap.getString("dishEditDescriptionLabel.text")); // NOI18N
        dishEditDescriptionLabel.setName("dishEditDescriptionLabel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        editDishDescriptionTextArea.setText(resourceMap.getString("editDishDescriptionTextArea.text")); // NOI18N
        editDishDescriptionTextArea.setName("editDishDescriptionTextArea"); // NOI18N
        jScrollPane2.setViewportView(editDishDescriptionTextArea);

        editDishDishPriceTextArea.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        editDishDishPriceTextArea.setText(resourceMap.getString("editDishDishPriceTextArea.text")); // NOI18N
        editDishDishPriceTextArea.setName("editDishDishPriceTextArea"); // NOI18N

        dishEditPriceLabel.setText(resourceMap.getString("dishEditPriceLabel.text")); // NOI18N
        dishEditPriceLabel.setName("dishEditPriceLabel"); // NOI18N

        dishIsVegetarianLabel.setText(resourceMap.getString("dishIsVegetarianLabel.text")); // NOI18N
        dishIsVegetarianLabel.setName("dishIsVegetarianLabel"); // NOI18N

        editDishIsVegetarianComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsVegetarianComboBox.setName("editDishIsVegetarianComboBox"); // NOI18N

        dishEditIsPSpicyLabel.setText(resourceMap.getString("dishEditIsPSpicyLabel.text")); // NOI18N
        dishEditIsPSpicyLabel.setName("dishEditIsPSpicyLabel"); // NOI18N

        editDishIsPsicyComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsPsicyComboBox.setName("editDishIsPsicyComboBox"); // NOI18N

        editDIshContainsNutsComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDIshContainsNutsComboBox.setName("editDIshContainsNutsComboBox"); // NOI18N

        dishEditContainsNutsLabel.setText(resourceMap.getString("dishEditContainsNutsLabel.text")); // NOI18N
        dishEditContainsNutsLabel.setName("dishEditContainsNutsLabel"); // NOI18N

        editDishContainsDairyComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishContainsDairyComboBox.setName("editDishContainsDairyComboBox"); // NOI18N

        dishEditContainsDairyLabel.setText(resourceMap.getString("dishEditContainsDairyLabel.text")); // NOI18N
        dishEditContainsDairyLabel.setName("dishEditContainsDairyLabel"); // NOI18N

        editDIshContainsGlutenComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDIshContainsGlutenComboBox.setName("editDIshContainsGlutenComboBox"); // NOI18N

        dishEditContainsGlutenLabel.setText(resourceMap.getString("dishEditContainsGlutenLabel.text")); // NOI18N
        dishEditContainsGlutenLabel.setName("dishEditContainsGlutenLabel"); // NOI18N

        dishEditIsActiveLabel.setText(resourceMap.getString("dishEditIsActiveLabel.text")); // NOI18N
        dishEditIsActiveLabel.setName("dishEditIsActiveLabel"); // NOI18N

        editDishIsDishActiveComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsDishActiveComboBox.setName("editDishIsDishActiveComboBox"); // NOI18N

        confirmDishEditButton.setText(resourceMap.getString("confirmDishEditButton.text")); // NOI18N
        confirmDishEditButton.setName("confirmDishEditButton"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dishEditDescriptionLabel)
                            .addComponent(dishEditNameLabel)
                            .addComponent(dishEditPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDishNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(editDishDishPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dishIsVegetarianLabel)
                            .addComponent(dishEditContainsNutsLabel)
                            .addComponent(dishEditIsPSpicyLabel)
                            .addComponent(dishEditContainsDairyLabel)
                            .addComponent(dishEditContainsGlutenLabel)
                            .addComponent(dishEditIsActiveLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDishIsDishActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishIsPsicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishIsVegetarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDIshContainsNutsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDishContainsDairyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editDIshContainsGlutenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(confirmDishEditButton))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dishEditNameLabel)
                    .addComponent(editDishNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dishEditDescriptionLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dishEditPriceLabel)
                    .addComponent(editDishDishPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dishIsVegetarianLabel)
                    .addComponent(editDishIsVegetarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsPsicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditIsPSpicyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDIshContainsNutsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsNutsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishContainsDairyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsDairyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDIshContainsGlutenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsGlutenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsDishActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditIsActiveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmDishEditButton)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        allActiveDishesTable.setModel(new DefaultTableModel());
        allActiveDishesTable.setName("allActiveDishesTable"); // NOI18N
        jScrollPane1.setViewportView(allActiveDishesTable);

        searchDishSearchButton.setText(resourceMap.getString("searchDishSearchButton.text")); // NOI18N
        searchDishSearchButton.setName("searchDishSearchButton"); // NOI18N

        searchDishTextBox.setText(resourceMap.getString("searchDishTextBox.text")); // NOI18N
        searchDishTextBox.setName("searchDishTextBox"); // NOI18N

        addNewDishButton.setText(resourceMap.getString("addNewDishButton.text")); // NOI18N
        addNewDishButton.setName("addNewDishButton"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewDishButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(searchDishTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchDishSearchButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewDishButton)
                    .addComponent(searchDishSearchButton)
                    .addComponent(searchDishTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout DishEditingPanelLayout = new javax.swing.GroupLayout(DishEditingPanel);
        DishEditingPanel.setLayout(DishEditingPanelLayout);
        DishEditingPanelLayout.setHorizontalGroup(
            DishEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        DishEditingPanelLayout.setVerticalGroup(
            DishEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("DishEditingPanel.TabConstraints.tabTitle"), DishEditingPanel); // NOI18N

        ExtrasEditingPanel.setName("ExtrasEditingPanel"); // NOI18N

        jSplitPane3.setDividerLocation(400);
        jSplitPane3.setName("jSplitPane3"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        editExtraExtraNameTextBox.setName("editExtraExtraNameTextBox"); // NOI18N

        editDishPriceTextBox.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        editDishPriceTextBox.setName("editDishPriceTextBox"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        editExtraExtraIsActiveComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editExtraExtraIsActiveComboBox.setName("editExtraExtraIsActiveComboBox"); // NOI18N

        confirmEditExtraButton.setText(resourceMap.getString("confirmEditExtraButton.text")); // NOI18N
        confirmEditExtraButton.setName("confirmEditExtraButton"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDishPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editExtraExtraNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(editExtraExtraIsActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmEditExtraButton))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(editExtraExtraNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraExtraIsActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmEditExtraButton)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(jPanel5);

        jPanel6.setName("jPanel6"); // NOI18N

        jScrollPane6.setName("jScrollPane6"); // NOI18N

        allRegisteredExtrasTable.setModel(new DefaultTableModel());
        allRegisteredExtrasTable.setName("allRegisteredExtrasTable"); // NOI18N
        jScrollPane6.setViewportView(allRegisteredExtrasTable);

        searchExtraSearchButton.setText(resourceMap.getString("searchExtraSearchButton.text")); // NOI18N
        searchExtraSearchButton.setName("searchExtraSearchButton"); // NOI18N

        searchExtraTextBox.setName("searchExtraTextBox"); // NOI18N

        createNewExtraButton.setText(resourceMap.getString("createNewExtraButton.text")); // NOI18N
        createNewExtraButton.setName("createNewExtraButton"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewExtraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(searchExtraTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchExtraSearchButton)
                .addContainerGap())
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewExtraButton)
                    .addComponent(searchExtraSearchButton)
                    .addComponent(searchExtraTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(jPanel6);

        javax.swing.GroupLayout ExtrasEditingPanelLayout = new javax.swing.GroupLayout(ExtrasEditingPanel);
        ExtrasEditingPanel.setLayout(ExtrasEditingPanelLayout);
        ExtrasEditingPanelLayout.setHorizontalGroup(
            ExtrasEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        ExtrasEditingPanelLayout.setVerticalGroup(
            ExtrasEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("ExtrasEditingPanel.TabConstraints.tabTitle"), ExtrasEditingPanel); // NOI18N

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(470, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        mainTabbedPane.addTab(resourceMap.getString("jScrollPane3.TabConstraints.tabTitle"), jScrollPane3); // NOI18N

        add(mainTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DishEditingPanel;
    private javax.swing.JPanel ExtrasEditingPanel;
    private javax.swing.JButton addNewDishButton;
    private javax.swing.JTable allActiveDishesTable;
    private javax.swing.JTable allRegisteredExtrasTable;
    private javax.swing.JButton confirmDishEditButton;
    private javax.swing.JButton confirmEditExtraButton;
    private javax.swing.JButton createNewExtraButton;
    private javax.swing.JLabel dishEditContainsDairyLabel;
    private javax.swing.JLabel dishEditContainsGlutenLabel;
    private javax.swing.JLabel dishEditContainsNutsLabel;
    private javax.swing.JLabel dishEditDescriptionLabel;
    private javax.swing.JLabel dishEditIsActiveLabel;
    private javax.swing.JLabel dishEditIsPSpicyLabel;
    private javax.swing.JLabel dishEditNameLabel;
    private javax.swing.JLabel dishEditPriceLabel;
    private javax.swing.JLabel dishIsVegetarianLabel;
    private javax.swing.JComboBox editDIshContainsGlutenComboBox;
    private javax.swing.JComboBox editDIshContainsNutsComboBox;
    private javax.swing.JComboBox editDishContainsDairyComboBox;
    private javax.swing.JTextPane editDishDescriptionTextArea;
    private javax.swing.JFormattedTextField editDishDishPriceTextArea;
    private javax.swing.JComboBox editDishIsDishActiveComboBox;
    private javax.swing.JComboBox editDishIsPsicyComboBox;
    private javax.swing.JComboBox editDishIsVegetarianComboBox;
    private javax.swing.JTextField editDishNameTextBox;
    private javax.swing.JFormattedTextField editDishPriceTextBox;
    private javax.swing.JComboBox editExtraExtraIsActiveComboBox;
    private javax.swing.JTextField editExtraExtraNameTextBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton searchDishSearchButton;
    private javax.swing.JTextField searchDishTextBox;
    private javax.swing.JButton searchExtraSearchButton;
    private javax.swing.JTextField searchExtraTextBox;
    // End of variables declaration//GEN-END:variables
}
