/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminView.java
 *
 * Created on 06.nov.2011, 13:44:26
 */
package pizzaProgram.gui.views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bart
 */
public class AdminView extends javax.swing.JPanel {

    /** Creates new form AdminView */
    public AdminView() {
        initComponents();
    }
    
    public String toString()
    {
        return "AdminView";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        DishEditingPanel = new javax.swing.JPanel();
        editDishesMainSplitPane = new javax.swing.JSplitPane();
        dishEditDishListJPanel = new javax.swing.JPanel();
        allActiveDishesDishTableScrollPane = new javax.swing.JScrollPane();
        allActiveDishesTable = new javax.swing.JTable();
        searchDishTextBox = new javax.swing.JTextField();
        addNewDishButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editDishScrollPane = new javax.swing.JScrollPane();
        editDishJPanel = new javax.swing.JPanel();
        dishEditNameLabel = new javax.swing.JLabel();
        editDishNameTextBox = new javax.swing.JTextField();
        dishEditDescriptionLabel = new javax.swing.JLabel();
        editDishDescriptionScrollPane = new javax.swing.JScrollPane();
        editDishDescriptionTextArea = new javax.swing.JTextPane();
        dishEditPriceLabel = new javax.swing.JLabel();
        dishIsVegetarianLabel = new javax.swing.JLabel();
        editDishIsVegetarianComboBox = new javax.swing.JComboBox();
        dishEditIsPSpicyLabel = new javax.swing.JLabel();
        editDishIsPsicyComboBox = new javax.swing.JComboBox();
        editDIshContainsNutsComboBox = new javax.swing.JComboBox();
        dishEditContainsNutsLabel = new javax.swing.JLabel();
        editDishContainsDairyComboBox = new javax.swing.JComboBox();
        dishEditContainsDairyLabel = new javax.swing.JLabel();
        editDIshContainsGlutenComboBox = new javax.swing.JComboBox();
        dishEditContainsGlutenLabel = new javax.swing.JLabel();
        dishEditIsActiveLabel = new javax.swing.JLabel();
        editDishIsDishActiveComboBox = new javax.swing.JComboBox();
        confirmDishEditButton = new javax.swing.JButton();
        editDishDishPriceTextArea = new javax.swing.JTextField();
        ExtrasEditingPanel = new javax.swing.JPanel();
        extrasMainSplitPane = new javax.swing.JSplitPane();
        editExtraJPanel = new javax.swing.JPanel();
        extraEditNameLabel = new javax.swing.JLabel();
        editExtraExtraNameTextBox = new javax.swing.JTextField();
        extraEditPriceTextBox = new javax.swing.JLabel();
        editExtraIsActiveLabel = new javax.swing.JLabel();
        editExtraExtraIsActiveComboBox = new javax.swing.JComboBox();
        confirmEditExtraButton = new javax.swing.JButton();
        editExtraExtraPriceTextArea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        editExtraExtraSelectionJPanel = new javax.swing.JPanel();
        allRegisteredExtrasScrollPane = new javax.swing.JScrollPane();
        allRegisteredExtrasTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        searchExtraTextBox = new javax.swing.JTextField();
        createNewExtraButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        orderEditingPanel = new javax.swing.JPanel();
        mainSplitPane = new javax.swing.JSplitPane();
        orderTablePanel = new javax.swing.JPanel();
        ordersTableScrollPane = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        orderReceiptPanel = new javax.swing.JPanel();
        receiptLabelScrollPane = new javax.swing.JScrollPane();
        orderReceiptLabel = new javax.swing.JLabel();
        settingsScrollPane = new javax.swing.JScrollPane();
        editSettingsJPanel = new javax.swing.JPanel();
        editSettingsNameOfRestaurantLabel = new javax.swing.JLabel();
        settingsEditNameOfRestaurantTextBox = new javax.swing.JTextField();
        editSettingsMinimumOrderPriceLabel = new javax.swing.JLabel();
        settingsEditMinimumPriceFreeDeliveryTextBox = new javax.swing.JTextField();
        editSettingsDeliveryPriceLabel = new javax.swing.JLabel();
        settingsDeliveryPriceTextBox = new javax.swing.JTextField();
        settingsApplyChangesButton = new javax.swing.JButton();
        settingsResetSettingsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        settingsEditAdressOfRestaurantTextBox = new javax.swing.JTextField();
        settingsEditCityOfRestaurantTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainTabbedPane.setName("mainTabbedPane"); // NOI18N

        DishEditingPanel.setName("DishEditingPanel"); // NOI18N

        editDishesMainSplitPane.setDividerLocation(400);
        editDishesMainSplitPane.setName("editDishesMainSplitPane"); // NOI18N

        dishEditDishListJPanel.setName("dishEditDishListJPanel"); // NOI18N

        allActiveDishesDishTableScrollPane.setName("allActiveDishesDishTableScrollPane"); // NOI18N

        allActiveDishesTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        allActiveDishesTable.setAutoCreateRowSorter(true);
        allActiveDishesTable.setModel(new DefaultTableModel());
        allActiveDishesTable.setName("allActiveDishesTable"); // NOI18N
        allActiveDishesDishTableScrollPane.setViewportView(allActiveDishesTable);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaProgram.core.PizzaProgram.class).getContext().getResourceMap(AdminView.class);
        searchDishTextBox.setText(resourceMap.getString("searchDishTextBox.text")); // NOI18N
        searchDishTextBox.setName("searchDishTextBox"); // NOI18N

        addNewDishButton.setText(resourceMap.getString("addNewDishButton.text")); // NOI18N
        addNewDishButton.setName("addNewDishButton"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout dishEditDishListJPanelLayout = new javax.swing.GroupLayout(dishEditDishListJPanel);
        dishEditDishListJPanel.setLayout(dishEditDishListJPanelLayout);
        dishEditDishListJPanelLayout.setHorizontalGroup(
            dishEditDishListJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishEditDishListJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewDishButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchDishTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(allActiveDishesDishTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        dishEditDishListJPanelLayout.setVerticalGroup(
            dishEditDishListJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishEditDishListJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishEditDishListJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewDishButton)
                    .addComponent(searchDishTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allActiveDishesDishTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        editDishesMainSplitPane.setLeftComponent(dishEditDishListJPanel);

        editDishScrollPane.setName("editDishScrollPane"); // NOI18N

        editDishJPanel.setName("editDishJPanel"); // NOI18N

        dishEditNameLabel.setText(resourceMap.getString("dishEditNameLabel.text")); // NOI18N
        dishEditNameLabel.setName("dishEditNameLabel"); // NOI18N

        editDishNameTextBox.setText(resourceMap.getString("editDishNameTextBox.text")); // NOI18N
        editDishNameTextBox.setName("editDishNameTextBox"); // NOI18N

        dishEditDescriptionLabel.setText(resourceMap.getString("dishEditDescriptionLabel.text")); // NOI18N
        dishEditDescriptionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dishEditDescriptionLabel.setName("dishEditDescriptionLabel"); // NOI18N

        editDishDescriptionScrollPane.setName("editDishDescriptionScrollPane"); // NOI18N

        editDishDescriptionTextArea.setText(resourceMap.getString("editDishDescriptionTextArea.text")); // NOI18N
        editDishDescriptionTextArea.setName("editDishDescriptionTextArea"); // NOI18N
        editDishDescriptionScrollPane.setViewportView(editDishDescriptionTextArea);

        dishEditPriceLabel.setText(resourceMap.getString("dishEditPriceLabel.text")); // NOI18N
        dishEditPriceLabel.setName("dishEditPriceLabel"); // NOI18N

        dishIsVegetarianLabel.setText(resourceMap.getString("dishIsVegetarianLabel.text")); // NOI18N
        dishIsVegetarianLabel.setName("dishIsVegetarianLabel"); // NOI18N

        editDishIsVegetarianComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsVegetarianComboBox.setName("editDishIsVegetarianComboBox"); // NOI18N

        dishEditIsPSpicyLabel.setText(resourceMap.getString("dishEditIsPSpicyLabel.text")); // NOI18N
        dishEditIsPSpicyLabel.setName("dishEditIsPSpicyLabel"); // NOI18N

        editDishIsPsicyComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsPsicyComboBox.setName("editDishIsPsicyComboBox"); // NOI18N

        editDIshContainsNutsComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDIshContainsNutsComboBox.setName("editDIshContainsNutsComboBox"); // NOI18N

        dishEditContainsNutsLabel.setText(resourceMap.getString("dishEditContainsNutsLabel.text")); // NOI18N
        dishEditContainsNutsLabel.setName("dishEditContainsNutsLabel"); // NOI18N

        editDishContainsDairyComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishContainsDairyComboBox.setName("editDishContainsDairyComboBox"); // NOI18N

        dishEditContainsDairyLabel.setText(resourceMap.getString("dishEditContainsDairyLabel.text")); // NOI18N
        dishEditContainsDairyLabel.setName("dishEditContainsDairyLabel"); // NOI18N

        editDIshContainsGlutenComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDIshContainsGlutenComboBox.setName("editDIshContainsGlutenComboBox"); // NOI18N

        dishEditContainsGlutenLabel.setText(resourceMap.getString("dishEditContainsGlutenLabel.text")); // NOI18N
        dishEditContainsGlutenLabel.setName("dishEditContainsGlutenLabel"); // NOI18N

        dishEditIsActiveLabel.setText(resourceMap.getString("dishEditIsActiveLabel.text")); // NOI18N
        dishEditIsActiveLabel.setName("dishEditIsActiveLabel"); // NOI18N

        editDishIsDishActiveComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editDishIsDishActiveComboBox.setName("editDishIsDishActiveComboBox"); // NOI18N

        confirmDishEditButton.setText(resourceMap.getString("confirmDishEditButton.text")); // NOI18N
        confirmDishEditButton.setName("confirmDishEditButton"); // NOI18N

        editDishDishPriceTextArea.setText(resourceMap.getString("editDishDishPriceTextArea.text")); // NOI18N
        editDishDishPriceTextArea.setName("editDishDishPriceTextArea"); // NOI18N

        javax.swing.GroupLayout editDishJPanelLayout = new javax.swing.GroupLayout(editDishJPanel);
        editDishJPanel.setLayout(editDishJPanelLayout);
        editDishJPanelLayout.setHorizontalGroup(
            editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDishJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editDishJPanelLayout.createSequentialGroup()
                        .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dishEditPriceLabel)
                            .addComponent(dishIsVegetarianLabel)
                            .addComponent(dishEditIsPSpicyLabel)
                            .addComponent(dishEditContainsNutsLabel)
                            .addComponent(dishEditContainsDairyLabel)
                            .addComponent(dishEditContainsGlutenLabel)
                            .addComponent(dishEditIsActiveLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(dishEditDescriptionLabel)
                    .addGroup(editDishJPanelLayout.createSequentialGroup()
                        .addComponent(dishEditNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmDishEditButton)
                    .addComponent(editDishNameTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(editDishDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(editDishDishPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDishIsDishActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDishIsPsicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDishIsVegetarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDIshContainsNutsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDishContainsDairyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editDIshContainsGlutenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        editDishJPanelLayout.setVerticalGroup(
            editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDishJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDishDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditDescriptionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishDishPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsVegetarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishIsVegetarianLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsPsicyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditIsPSpicyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDIshContainsNutsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsNutsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishContainsDairyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsDairyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDIshContainsGlutenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditContainsGlutenLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editDishJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDishIsDishActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishEditIsActiveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmDishEditButton)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        editDishScrollPane.setViewportView(editDishJPanel);

        editDishesMainSplitPane.setRightComponent(editDishScrollPane);

        javax.swing.GroupLayout DishEditingPanelLayout = new javax.swing.GroupLayout(DishEditingPanel);
        DishEditingPanel.setLayout(DishEditingPanelLayout);
        DishEditingPanelLayout.setHorizontalGroup(
            DishEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editDishesMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        DishEditingPanelLayout.setVerticalGroup(
            DishEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editDishesMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("DishEditingPanel.TabConstraints.tabTitle"), DishEditingPanel); // NOI18N

        ExtrasEditingPanel.setName("ExtrasEditingPanel"); // NOI18N

        extrasMainSplitPane.setDividerLocation(400);
        extrasMainSplitPane.setName("extrasMainSplitPane"); // NOI18N

        editExtraJPanel.setName("editExtraJPanel"); // NOI18N

        extraEditNameLabel.setText(resourceMap.getString("extraEditNameLabel.text")); // NOI18N
        extraEditNameLabel.setName("extraEditNameLabel"); // NOI18N

        editExtraExtraNameTextBox.setName("editExtraExtraNameTextBox"); // NOI18N

        extraEditPriceTextBox.setText(resourceMap.getString("extraEditPriceTextBox.text")); // NOI18N
        extraEditPriceTextBox.setName("extraEditPriceTextBox"); // NOI18N

        editExtraIsActiveLabel.setText(resourceMap.getString("editExtraIsActiveLabel.text")); // NOI18N
        editExtraIsActiveLabel.setName("editExtraIsActiveLabel"); // NOI18N

        editExtraExtraIsActiveComboBox.setModel(new javax.swing.DefaultComboBoxModel());
        editExtraExtraIsActiveComboBox.setName("editExtraExtraIsActiveComboBox"); // NOI18N

        confirmEditExtraButton.setText(resourceMap.getString("confirmEditExtraButton.text")); // NOI18N
        confirmEditExtraButton.setName("confirmEditExtraButton"); // NOI18N

        editExtraExtraPriceTextArea.setText(resourceMap.getString("editExtraExtraPriceTextArea.text")); // NOI18N
        editExtraExtraPriceTextArea.setName("editExtraExtraPriceTextArea"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout editExtraJPanelLayout = new javax.swing.GroupLayout(editExtraJPanel);
        editExtraJPanel.setLayout(editExtraJPanelLayout);
        editExtraJPanelLayout.setHorizontalGroup(
            editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraJPanelLayout.createSequentialGroup()
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editExtraJPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(extraEditPriceTextBox)
                            .addComponent(extraEditNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editExtraExtraPriceTextArea)
                            .addComponent(editExtraExtraNameTextBox)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)))
                    .addGroup(editExtraJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(editExtraIsActiveLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmEditExtraButton)
                            .addComponent(editExtraExtraIsActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        editExtraJPanelLayout.setVerticalGroup(
            editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraExtraNameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extraEditNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraExtraPriceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extraEditPriceTextBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editExtraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editExtraIsActiveLabel)
                    .addComponent(editExtraExtraIsActiveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmEditExtraButton)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        extrasMainSplitPane.setRightComponent(editExtraJPanel);

        editExtraExtraSelectionJPanel.setName("editExtraExtraSelectionJPanel"); // NOI18N

        allRegisteredExtrasScrollPane.setName("allRegisteredExtrasScrollPane"); // NOI18N

        allRegisteredExtrasTable.setAutoCreateRowSorter(true);
        allRegisteredExtrasTable.setModel(new DefaultTableModel());
        allRegisteredExtrasTable.setName("allRegisteredExtrasTable"); // NOI18N
        allRegisteredExtrasScrollPane.setViewportView(allRegisteredExtrasTable);

        searchExtraTextBox.setText(resourceMap.getString("searchExtraTextBox.text")); // NOI18N
        searchExtraTextBox.setName("searchExtraTextBox"); // NOI18N

        createNewExtraButton.setText(resourceMap.getString("createNewExtraButton.text")); // NOI18N
        createNewExtraButton.setName("createNewExtraButton"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout editExtraExtraSelectionJPanelLayout = new javax.swing.GroupLayout(editExtraExtraSelectionJPanel);
        editExtraExtraSelectionJPanel.setLayout(editExtraExtraSelectionJPanelLayout);
        editExtraExtraSelectionJPanelLayout.setHorizontalGroup(
            editExtraExtraSelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraExtraSelectionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNewExtraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchExtraTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(allRegisteredExtrasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        editExtraExtraSelectionJPanelLayout.setVerticalGroup(
            editExtraExtraSelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editExtraExtraSelectionJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editExtraExtraSelectionJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewExtraButton)
                    .addComponent(searchExtraTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allRegisteredExtrasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        extrasMainSplitPane.setLeftComponent(editExtraExtraSelectionJPanel);

        javax.swing.GroupLayout ExtrasEditingPanelLayout = new javax.swing.GroupLayout(ExtrasEditingPanel);
        ExtrasEditingPanel.setLayout(ExtrasEditingPanelLayout);
        ExtrasEditingPanelLayout.setHorizontalGroup(
            ExtrasEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extrasMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        ExtrasEditingPanelLayout.setVerticalGroup(
            ExtrasEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(extrasMainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("ExtrasEditingPanel.TabConstraints.tabTitle"), ExtrasEditingPanel); // NOI18N

        orderEditingPanel.setName("orderEditingPanel"); // NOI18N

        mainSplitPane.setDividerLocation(400);
        mainSplitPane.setName("mainSplitPane"); // NOI18N

        orderTablePanel.setName("orderTablePanel"); // NOI18N

        ordersTableScrollPane.setName("ordersTableScrollPane"); // NOI18N

        ordersTable.setModel(new DefaultTableModel());
        ordersTable.setName("ordersTable"); // NOI18N
        ordersTableScrollPane.setViewportView(ordersTable);

        javax.swing.GroupLayout orderTablePanelLayout = new javax.swing.GroupLayout(orderTablePanel);
        orderTablePanel.setLayout(orderTablePanelLayout);
        orderTablePanelLayout.setHorizontalGroup(
            orderTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        orderTablePanelLayout.setVerticalGroup(
            orderTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordersTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        mainSplitPane.setLeftComponent(orderTablePanel);

        orderReceiptPanel.setName("orderReceiptPanel"); // NOI18N

        receiptLabelScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        receiptLabelScrollPane.setName("receiptLabelScrollPane"); // NOI18N

        orderReceiptLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        orderReceiptLabel.setText(resourceMap.getString("orderReceiptLabel.text")); // NOI18N
        orderReceiptLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        orderReceiptLabel.setName("orderReceiptLabel"); // NOI18N
        receiptLabelScrollPane.setViewportView(orderReceiptLabel);

        javax.swing.GroupLayout orderReceiptPanelLayout = new javax.swing.GroupLayout(orderReceiptPanel);
        orderReceiptPanel.setLayout(orderReceiptPanelLayout);
        orderReceiptPanelLayout.setHorizontalGroup(
            orderReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receiptLabelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        orderReceiptPanelLayout.setVerticalGroup(
            orderReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receiptLabelScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        mainSplitPane.setRightComponent(orderReceiptPanel);

        javax.swing.GroupLayout orderEditingPanelLayout = new javax.swing.GroupLayout(orderEditingPanel);
        orderEditingPanel.setLayout(orderEditingPanelLayout);
        orderEditingPanelLayout.setHorizontalGroup(
            orderEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        orderEditingPanelLayout.setVerticalGroup(
            orderEditingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab(resourceMap.getString("orderEditingPanel.TabConstraints.tabTitle"), orderEditingPanel); // NOI18N

        settingsScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        settingsScrollPane.setName("settingsScrollPane"); // NOI18N

        editSettingsJPanel.setName("editSettingsJPanel"); // NOI18N

        editSettingsNameOfRestaurantLabel.setText(resourceMap.getString("editSettingsNameOfRestaurantLabel.text")); // NOI18N
        editSettingsNameOfRestaurantLabel.setName("editSettingsNameOfRestaurantLabel"); // NOI18N

        settingsEditNameOfRestaurantTextBox.setText(resourceMap.getString("settingsEditNameOfRestaurantTextBox.text")); // NOI18N
        settingsEditNameOfRestaurantTextBox.setName("settingsEditNameOfRestaurantTextBox"); // NOI18N

        editSettingsMinimumOrderPriceLabel.setText(resourceMap.getString("editSettingsMinimumOrderPriceLabel.text")); // NOI18N
        editSettingsMinimumOrderPriceLabel.setName("editSettingsMinimumOrderPriceLabel"); // NOI18N

        settingsEditMinimumPriceFreeDeliveryTextBox.setText(resourceMap.getString("settingsEditMinimumPriceFreeDeliveryTextBox.text")); // NOI18N
        settingsEditMinimumPriceFreeDeliveryTextBox.setName("settingsEditMinimumPriceFreeDeliveryTextBox"); // NOI18N

        editSettingsDeliveryPriceLabel.setText(resourceMap.getString("editSettingsDeliveryPriceLabel.text")); // NOI18N
        editSettingsDeliveryPriceLabel.setName("editSettingsDeliveryPriceLabel"); // NOI18N

        settingsDeliveryPriceTextBox.setText(resourceMap.getString("settingsDeliveryPriceTextBox.text")); // NOI18N
        settingsDeliveryPriceTextBox.setName("settingsDeliveryPriceTextBox"); // NOI18N

        settingsApplyChangesButton.setText(resourceMap.getString("settingsApplyChangesButton.text")); // NOI18N
        settingsApplyChangesButton.setName("settingsApplyChangesButton"); // NOI18N

        settingsResetSettingsButton.setText(resourceMap.getString("settingsResetSettingsButton.text")); // NOI18N
        settingsResetSettingsButton.setName("settingsResetSettingsButton"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        settingsEditAdressOfRestaurantTextBox.setText(resourceMap.getString("settingsEditAdressOfRestaurantTextBox.text")); // NOI18N
        settingsEditAdressOfRestaurantTextBox.setName("settingsEditAdressOfRestaurantTextBox"); // NOI18N

        settingsEditCityOfRestaurantTextBox.setText(resourceMap.getString("settingsEditCityOfRestaurantTextBox.text")); // NOI18N
        settingsEditCityOfRestaurantTextBox.setName("settingsEditCityOfRestaurantTextBox"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        javax.swing.GroupLayout editSettingsJPanelLayout = new javax.swing.GroupLayout(editSettingsJPanel);
        editSettingsJPanel.setLayout(editSettingsJPanelLayout);
        editSettingsJPanelLayout.setHorizontalGroup(
            editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(editSettingsNameOfRestaurantLabel)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(settingsEditAdressOfRestaurantTextBox)
                            .addComponent(settingsEditNameOfRestaurantTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(settingsEditCityOfRestaurantTextBox)))
                    .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(editSettingsDeliveryPriceLabel))
                            .addComponent(editSettingsMinimumOrderPriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                                .addComponent(settingsResetSettingsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(settingsApplyChangesButton))
                            .addComponent(settingsDeliveryPriceTextBox)
                            .addComponent(settingsEditMinimumPriceFreeDeliveryTextBox))))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        editSettingsJPanelLayout.setVerticalGroup(
            editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editSettingsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsEditNameOfRestaurantTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSettingsNameOfRestaurantLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(settingsEditAdressOfRestaurantTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsEditCityOfRestaurantTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsEditMinimumPriceFreeDeliveryTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSettingsMinimumOrderPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsDeliveryPriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSettingsDeliveryPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editSettingsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsResetSettingsButton)
                    .addComponent(settingsApplyChangesButton))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        settingsScrollPane.setViewportView(editSettingsJPanel);

        mainTabbedPane.addTab(resourceMap.getString("settingsScrollPane.TabConstraints.tabTitle"), settingsScrollPane); // NOI18N

        add(mainTabbedPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>
    // Variables declaration - do not modify
    public static javax.swing.JPanel DishEditingPanel;
    public static javax.swing.JPanel ExtrasEditingPanel;
    public static javax.swing.JButton addNewDishButton;
    public static javax.swing.JScrollPane allActiveDishesDishTableScrollPane;
    public static javax.swing.JTable allActiveDishesTable;
    public static javax.swing.JScrollPane allRegisteredExtrasScrollPane;
    public static javax.swing.JTable allRegisteredExtrasTable;
    public static javax.swing.JButton confirmDishEditButton;
    public static javax.swing.JButton confirmEditExtraButton;
    public static javax.swing.JButton createNewExtraButton;
    public static javax.swing.JLabel dishEditContainsDairyLabel;
    public static javax.swing.JLabel dishEditContainsGlutenLabel;
    public static javax.swing.JLabel dishEditContainsNutsLabel;
    public static javax.swing.JLabel dishEditDescriptionLabel;
    public static javax.swing.JPanel dishEditDishListJPanel;
    public static javax.swing.JLabel dishEditIsActiveLabel;
    public static javax.swing.JLabel dishEditIsPSpicyLabel;
    public static javax.swing.JLabel dishEditNameLabel;
    public static javax.swing.JLabel dishEditPriceLabel;
    public static javax.swing.JLabel dishIsVegetarianLabel;
    public static javax.swing.JComboBox editDIshContainsGlutenComboBox;
    public static javax.swing.JComboBox editDIshContainsNutsComboBox;
    public static javax.swing.JComboBox editDishContainsDairyComboBox;
    public static javax.swing.JScrollPane editDishDescriptionScrollPane;
    public static javax.swing.JTextPane editDishDescriptionTextArea;
    public static javax.swing.JTextField editDishDishPriceTextArea;
    public static javax.swing.JComboBox editDishIsDishActiveComboBox;
    public static javax.swing.JComboBox editDishIsPsicyComboBox;
    public static javax.swing.JComboBox editDishIsVegetarianComboBox;
    public static javax.swing.JPanel editDishJPanel;
    public static javax.swing.JTextField editDishNameTextBox;
    public static javax.swing.JScrollPane editDishScrollPane;
    public static javax.swing.JSplitPane editDishesMainSplitPane;
    public static javax.swing.JComboBox editExtraExtraIsActiveComboBox;
    public static javax.swing.JTextField editExtraExtraNameTextBox;
    public static javax.swing.JTextField editExtraExtraPriceTextArea;
    public static javax.swing.JPanel editExtraExtraSelectionJPanel;
    public static javax.swing.JLabel editExtraIsActiveLabel;
    public static javax.swing.JPanel editExtraJPanel;
    public static javax.swing.JLabel editSettingsDeliveryPriceLabel;
    public static javax.swing.JPanel editSettingsJPanel;
    public static javax.swing.JLabel editSettingsMinimumOrderPriceLabel;
    public static javax.swing.JLabel editSettingsNameOfRestaurantLabel;
    public static javax.swing.JLabel extraEditNameLabel;
    public static javax.swing.JLabel extraEditPriceTextBox;
    public static javax.swing.JSplitPane extrasMainSplitPane;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JSplitPane mainSplitPane;
    public static javax.swing.JTabbedPane mainTabbedPane;
    public static javax.swing.JPanel orderEditingPanel;
    public static javax.swing.JLabel orderReceiptLabel;
    public static javax.swing.JPanel orderReceiptPanel;
    public static javax.swing.JPanel orderTablePanel;
    public static javax.swing.JTable ordersTable;
    public static javax.swing.JScrollPane ordersTableScrollPane;
    public static javax.swing.JScrollPane receiptLabelScrollPane;
    public static javax.swing.JTextField searchDishTextBox;
    public static javax.swing.JTextField searchExtraTextBox;
    public static javax.swing.JButton settingsApplyChangesButton;
    public static javax.swing.JTextField settingsDeliveryPriceTextBox;
    public static javax.swing.JTextField settingsEditAdressOfRestaurantTextBox;
    public static javax.swing.JTextField settingsEditCityOfRestaurantTextBox;
    public static javax.swing.JTextField settingsEditMinimumPriceFreeDeliveryTextBox;
    public static javax.swing.JTextField settingsEditNameOfRestaurantTextBox;
    public static javax.swing.JButton settingsResetSettingsButton;
    public static javax.swing.JScrollPane settingsScrollPane;
    // End of variables declaration
}
