/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderViewNew.java
 *
 * Created on 21.okt.2011, 13:05:40
 */
package pizzaProgram.gui.views;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bart
 */
public class OrderView extends javax.swing.JPanel {

    /** Creates new form OrderViewNew */
    public OrderView() {
        initComponents();
    }
 public String toString()
    {
        return "OrderView";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainPanel.setName("mainPanel"); // NOI18N

        mainSplitPane.setDividerLocation(200);
        mainSplitPane.setDoubleBuffered(true);
        mainSplitPane.setName("mainSplitPane"); // NOI18N

        customerLookupUI.setName("customerLookupUI"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaProgram.core.PizzaProgram.class).getContext().getResourceMap(OrderView.class);
        newCustomerButton.setText(resourceMap.getString("newCustomerButton.text")); // NOI18N
        newCustomerButton.setName("newCustomerButton"); // NOI18N

        searchCustomerTextArea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchCustomerTextArea.setName("searchCustomerTextArea"); // NOI18N

        searchCustomerSearchButton.setText(resourceMap.getString("searchCustomerSearchButton.text")); // NOI18N
        searchCustomerSearchButton.setName("searchCustomerSearchButton"); // NOI18N

        customerListScrollPane.setName("customerListScrollPane"); // NOI18N

        customerList.setModel(new DefaultListModel());
        customerList.setName("customerList"); // NOI18N
        customerListScrollPane.setViewportView(customerList);

        customerInformationScrollPane.setName("customerInformationScrollPane"); // NOI18N

        customerInformationTextArea.setColumns(20);
        customerInformationTextArea.setRows(4);
        customerInformationTextArea.setFocusable(false);
        customerInformationTextArea.setName("customerInformationTextArea"); // NOI18N
        customerInformationScrollPane.setViewportView(customerInformationTextArea);

        selectCustomerButton.setText(resourceMap.getString("selectCustomerButton.text")); // NOI18N
        selectCustomerButton.setName("selectCustomerButton"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout customerLookupUILayout = new javax.swing.GroupLayout(customerLookupUI);
        customerLookupUI.setLayout(customerLookupUILayout);
        customerLookupUILayout.setHorizontalGroup(
            customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLookupUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerInformationScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLookupUILayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(selectCustomerButton))
                    .addComponent(newCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLookupUILayout.createSequentialGroup()
                        .addComponent(searchCustomerTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCustomerSearchButton))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        customerLookupUILayout.setVerticalGroup(
            customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLookupUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCustomerSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerInformationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCustomerButton)
                .addContainerGap())
        );

        mainSplitPane.setLeftComponent(customerLookupUI);

        orderCreationUI.setName("orderCreationUI"); // NOI18N

        orderCreationUIVerticalSplitPane.setDividerLocation(200);
        orderCreationUIVerticalSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        orderCreationUIVerticalSplitPane.setName("orderCreationUIVerticalSplitPane"); // NOI18N

        dishSelectionArea.setName("dishSelectionArea"); // NOI18N

        addDishButton.setText(resourceMap.getString("addDishButton.text")); // NOI18N
        addDishButton.setName("addDishButton"); // NOI18N

        extrasSelectionSectionLabel.setText(resourceMap.getString("extrasSelectionSectionLabel.text")); // NOI18N
        extrasSelectionSectionLabel.setName("extrasSelectionSectionLabel"); // NOI18N

        dishSelectionSectionLabel.setText(resourceMap.getString("dishSelectionSectionLabel.text")); // NOI18N
        dishSelectionSectionLabel.setName("dishSelectionSectionLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        dishSelectionList.setModel(new DefaultListModel());
        dishSelectionList.setName("dishSelectionList"); // NOI18N
        jScrollPane1.setViewportView(dishSelectionList);

        DishSearchTextBox.setText(resourceMap.getString("DishSearchTextBox.text")); // NOI18N
        DishSearchTextBox.setName("DishSearchTextBox"); // NOI18N

        extrasSearchTextField.setText(resourceMap.getString("extrasSearchTextField.text")); // NOI18N
        extrasSearchTextField.setName("extrasSearchTextField"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        extrasSelectionList.setModel(new DefaultListModel());
        extrasSelectionList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        extrasSelectionList.setName("extrasSelectionList"); // NOI18N
        jScrollPane2.setViewportView(extrasSelectionList);

        dishSelectionSearchButton.setText(resourceMap.getString("dishSelectionSearchButton.text")); // NOI18N
        dishSelectionSearchButton.setName("dishSelectionSearchButton"); // NOI18N

        extrasSearchButton.setText(resourceMap.getString("extrasSearchButton.text")); // NOI18N
        extrasSearchButton.setName("extrasSearchButton"); // NOI18N

        javax.swing.GroupLayout dishSelectionAreaLayout = new javax.swing.GroupLayout(dishSelectionArea);
        dishSelectionArea.setLayout(dishSelectionAreaLayout);
        dishSelectionAreaLayout.setHorizontalGroup(
            dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                        .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dishSelectionSectionLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dishSelectionAreaLayout.createSequentialGroup()
                                .addComponent(DishSearchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dishSelectionSearchButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extrasSelectionSectionLabel)
                            .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                                .addComponent(extrasSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extrasSearchButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)))
                    .addComponent(addDishButton))
                .addContainerGap())
        );
        dishSelectionAreaLayout.setVerticalGroup(
            dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishSelectionAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dishSelectionSectionLabel)
                    .addComponent(extrasSelectionSectionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DishSearchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extrasSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dishSelectionSearchButton)
                    .addComponent(extrasSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDishButton)
                .addContainerGap())
        );

        orderCreationUIVerticalSplitPane.setTopComponent(dishSelectionArea);

        orderOverviewUI.setName("orderOverviewUI"); // NOI18N

        orderContentsTableScrollPane.setName("orderContentsTableScrollPane"); // NOI18N

        orderContentsTable.setAutoCreateRowSorter(true);
        orderContentsTable.setModel(new DefaultTableModel());
        orderContentsTable.setColumnSelectionAllowed(true);
        orderContentsTable.setName("orderContentsTable"); // NOI18N
        orderContentsTableScrollPane.setViewportView(orderContentsTable);

        orderCommentsTextAreaLabel.setText(resourceMap.getString("orderCommentsTextAreaLabel.text")); // NOI18N
        orderCommentsTextAreaLabel.setName("orderCommentsTextAreaLabel"); // NOI18N

        orderCommentsTextAreaScrollPane.setName("orderCommentsTextAreaScrollPane"); // NOI18N

        orderCommentsTextArea.setColumns(20);
        orderCommentsTextArea.setLineWrap(true);
        orderCommentsTextArea.setRows(2);
        orderCommentsTextArea.setName("orderCommentsTextArea"); // NOI18N
        orderCommentsTextAreaScrollPane.setViewportView(orderCommentsTextArea);

        resetOrderButton.setText(resourceMap.getString("resetOrderButton.text")); // NOI18N
        resetOrderButton.setName("resetOrderButton"); // NOI18N

        confirmOrderButton.setText(resourceMap.getString("confirmOrderButton.text")); // NOI18N
        confirmOrderButton.setName("confirmOrderButton"); // NOI18N

        deleteSelectedOrderDishButton.setText(resourceMap.getString("deleteSelectedOrderDishButton.text")); // NOI18N
        deleteSelectedOrderDishButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
        deleteSelectedOrderDishButton.setName("deleteSelectedOrderDishButton"); // NOI18N

        duplicateSelectedOrderDishButton.setText(resourceMap.getString("duplicateSelectedOrderDishButton.text")); // NOI18N
        duplicateSelectedOrderDishButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
        duplicateSelectedOrderDishButton.setName("duplicateSelectedOrderDishButton"); // NOI18N

        deliveryMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Delivery at home", "Pick up at restaurant"}));
        deliveryMethodComboBox.setName("deliveryMethodComboBox"); // NOI18N

        javax.swing.GroupLayout orderOverviewUILayout = new javax.swing.GroupLayout(orderOverviewUI);
        orderOverviewUI.setLayout(orderOverviewUILayout);
        orderOverviewUILayout.setHorizontalGroup(
            orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                        .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(orderOverviewUILayout.createSequentialGroup()
                                .addComponent(orderCommentsTextAreaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE))
                            .addGroup(orderOverviewUILayout.createSequentialGroup()
                                .addComponent(deliveryMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(duplicateSelectedOrderDishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSelectedOrderDishButton))
                    .addComponent(orderCommentsTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                        .addComponent(resetOrderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmOrderButton)))
                .addContainerGap())
            .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        orderOverviewUILayout.setVerticalGroup(
            orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteSelectedOrderDishButton)
                        .addComponent(duplicateSelectedOrderDishButton)
                        .addComponent(deliveryMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderCommentsTextAreaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmOrderButton)
                    .addComponent(resetOrderButton))
                .addContainerGap())
        );

        orderCreationUIVerticalSplitPane.setRightComponent(orderOverviewUI);

        javax.swing.GroupLayout orderCreationUILayout = new javax.swing.GroupLayout(orderCreationUI);
        orderCreationUI.setLayout(orderCreationUILayout);
        orderCreationUILayout.setHorizontalGroup(
            orderCreationUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderCreationUIVerticalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        orderCreationUILayout.setVerticalGroup(
            orderCreationUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderCreationUIVerticalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        mainSplitPane.setRightComponent(orderCreationUI);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTextField DishSearchTextBox = new javax.swing.JTextField();
    public static final javax.swing.JButton addDishButton = new javax.swing.JButton();
    public static final javax.swing.JButton confirmOrderButton = new javax.swing.JButton();
    public static final javax.swing.JScrollPane customerInformationScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTextArea customerInformationTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JList customerList = new javax.swing.JList();
    public static final javax.swing.JScrollPane customerListScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel customerLookupUI = new javax.swing.JPanel();
    public static final javax.swing.JButton deleteSelectedOrderDishButton = new javax.swing.JButton();
    public static final javax.swing.JComboBox deliveryMethodComboBox = new javax.swing.JComboBox();
    public static final javax.swing.JPanel dishSelectionArea = new javax.swing.JPanel();
    public static final javax.swing.JList dishSelectionList = new javax.swing.JList();
    public static final javax.swing.JButton dishSelectionSearchButton = new javax.swing.JButton();
    public static final javax.swing.JLabel dishSelectionSectionLabel = new javax.swing.JLabel();
    public static final javax.swing.JButton duplicateSelectedOrderDishButton = new javax.swing.JButton();
    public static final javax.swing.JButton extrasSearchButton = new javax.swing.JButton();
    public static final javax.swing.JTextField extrasSearchTextField = new javax.swing.JTextField();
    public static final javax.swing.JList extrasSelectionList = new javax.swing.JList();
    public static final javax.swing.JLabel extrasSelectionSectionLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public static final javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel mainPanel = new javax.swing.JPanel();
    public static final javax.swing.JSplitPane mainSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JButton newCustomerButton = new javax.swing.JButton();
    public static final javax.swing.JTextArea orderCommentsTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JLabel orderCommentsTextAreaLabel = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane orderCommentsTextAreaScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTable orderContentsTable = new javax.swing.JTable(){
        public boolean isCellEditable(int rowIndex, int colIndex) {
            return false; //Disallow the editing of any cell
        }
    };
    public static final javax.swing.JScrollPane orderContentsTableScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel orderCreationUI = new javax.swing.JPanel();
    public static final javax.swing.JSplitPane orderCreationUIVerticalSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JPanel orderOverviewUI = new javax.swing.JPanel();
    public static final javax.swing.JButton resetOrderButton = new javax.swing.JButton();
    public static final javax.swing.JButton searchCustomerSearchButton = new javax.swing.JButton();
    public static final javax.swing.JTextField searchCustomerTextArea = new javax.swing.JTextField();
    public static final javax.swing.JButton selectCustomerButton = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
