/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderViewNew.java
 *
 * Created on 21.okt.2011, 13:05:40
 */
package pizzaProgram.gui.views;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bart
 */
public class OrderView extends javax.swing.JPanel {

    /** Creates new form OrderViewNew */
    public OrderView() {
        initComponents();
    }
 public String toString()
    {
        return "OrderView";
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainPanel.setName("mainPanel"); // NOI18N

        mainSplitPane.setDividerLocation(260);
        mainSplitPane.setDoubleBuffered(true);
        mainSplitPane.setName("mainSplitPane"); // NOI18N

        customerLookupUI.setName("customerLookupUI"); // NOI18N
        customerLookupUI.setPreferredSize(new java.awt.Dimension(220, 512));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaProgram.core.PizzaProgram.class).getContext().getResourceMap(OrderView.class);
        newCustomerButton.setText(resourceMap.getString("newCustomerButton.text")); // NOI18N
        newCustomerButton.setName("newCustomerButton"); // NOI18N

        searchCustomerTextArea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchCustomerTextArea.setText(resourceMap.getString("searchCustomerTextArea.text")); // NOI18N
        searchCustomerTextArea.setName("searchCustomerTextArea"); // NOI18N

        customerListScrollPane.setName("customerListScrollPane"); // NOI18N

        customerList.setModel(new DefaultListModel());
        customerList.setName("customerList"); // NOI18N
        customerListScrollPane.setViewportView(customerList);

        customerInformationScrollPane.setName("customerInformationScrollPane"); // NOI18N

        customerInformationTextArea.setColumns(20);
        customerInformationTextArea.setRows(4);
        customerInformationTextArea.setFocusable(false);
        customerInformationTextArea.setName("customerInformationTextArea"); // NOI18N
        customerInformationScrollPane.setViewportView(customerInformationTextArea);

        selectCustomerButton.setText(resourceMap.getString("selectCustomerButton.text")); // NOI18N
        selectCustomerButton.setName("selectCustomerButton"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        deleteCustomerButton.setText(resourceMap.getString("deleteCustomerButton.text")); // NOI18N
        deleteCustomerButton.setName("deleteCustomerButton"); // NOI18N

        changeCustomerButton.setText(resourceMap.getString("changeCustomerButton.text")); // NOI18N
        changeCustomerButton.setName("changeCustomerButton"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout customerLookupUILayout = new javax.swing.GroupLayout(customerLookupUI);
        customerLookupUI.setLayout(customerLookupUILayout);
        customerLookupUILayout.setHorizontalGroup(
            customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLookupUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(customerInformationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(87, 87, 87))
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(deleteCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLookupUILayout.createSequentialGroup()
                        .addComponent(newCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeCustomerButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLookupUILayout.createSequentialGroup()
                        .addComponent(selectCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCustomerTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        customerLookupUILayout.setVerticalGroup(
            customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLookupUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeCustomerButton)
                    .addComponent(newCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(customerLookupUILayout.createSequentialGroup()
                        .addComponent(deleteCustomerButton)
                        .addGap(18, 18, 18)))
                .addComponent(customerInformationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCustomerButton)
                .addContainerGap())
        );

        mainSplitPane.setLeftComponent(customerLookupUI);

        orderCreationUI.setName("orderCreationUI"); // NOI18N

        orderCreationUIVerticalSplitPane.setDividerLocation(400);
        orderCreationUIVerticalSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        orderCreationUIVerticalSplitPane.setName("orderCreationUIVerticalSplitPane"); // NOI18N

        dishSelectionArea.setName("dishSelectionArea"); // NOI18N

        addDishButton.setText(resourceMap.getString("addDishButton.text")); // NOI18N
        addDishButton.setName("addDishButton"); // NOI18N

        extrasSelectionSectionLabel.setText(resourceMap.getString("extrasSelectionSectionLabel.text")); // NOI18N
        extrasSelectionSectionLabel.setName("extrasSelectionSectionLabel"); // NOI18N

        dishSelectionSectionLabel.setText(resourceMap.getString("dishSelectionSectionLabel.text")); // NOI18N
        dishSelectionSectionLabel.setName("dishSelectionSectionLabel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        dishSelectionList.setModel(new DefaultListModel());
        dishSelectionList.setName("dishSelectionList"); // NOI18N
        jScrollPane1.setViewportView(dishSelectionList);

        dishSearchTextBox.setText(resourceMap.getString("dishSearchTextBox.text")); // NOI18N
        dishSearchTextBox.setName("dishSearchTextBox"); // NOI18N

        extrasSearchTextField.setText(resourceMap.getString("extrasSearchTextField.text")); // NOI18N
        extrasSearchTextField.setName("extrasSearchTextField"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        extrasSelectionList.setModel(new DefaultListModel());
        extrasSelectionList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        extrasSelectionList.setName("extrasSelectionList"); // NOI18N
        jScrollPane2.setViewportView(extrasSelectionList);

        dishDescriptionArea.setName("dishDescriptionArea"); // NOI18N

        dishDescriptionLabel.setText(resourceMap.getString("dishDescriptionLabel.text")); // NOI18N
        dishDescriptionLabel.setName("dishDescriptionLabel"); // NOI18N

        dishContainsGlutenLabel.setText(resourceMap.getString("dishContainsGlutenLabel.text")); // NOI18N
        dishContainsGlutenLabel.setName("dishContainsGlutenLabel"); // NOI18N

        dishContainsGlutenText.setText(resourceMap.getString("dishContainsGlutenText.text")); // NOI18N
        dishContainsGlutenText.setName("dishContainsGlutenText"); // NOI18N

        dishContainsNutsLabel.setText(resourceMap.getString("dishContainsNutsLabel.text")); // NOI18N
        dishContainsNutsLabel.setName("dishContainsNutsLabel"); // NOI18N

        dishContainsNutsText.setText(resourceMap.getString("dishContainsNutsText.text")); // NOI18N
        dishContainsNutsText.setName("dishContainsNutsText"); // NOI18N

        dishContainsDairyLabel.setText(resourceMap.getString("dishContainsDairyLabel.text")); // NOI18N
        dishContainsDairyLabel.setName("dishContainsDairyLabel"); // NOI18N

        dishContainsDairyText.setText(resourceMap.getString("dishContainsDairyText.text")); // NOI18N
        dishContainsDairyText.setName("dishContainsDairyText"); // NOI18N

        dishIsVegetarianLabel.setText(resourceMap.getString("dishIsVegetarianLabel.text")); // NOI18N
        dishIsVegetarianLabel.setName("dishIsVegetarianLabel"); // NOI18N

        dishIsSpicyLabel.setText(resourceMap.getString("dishIsSpicyLabel.text")); // NOI18N
        dishIsSpicyLabel.setName("dishIsSpicyLabel"); // NOI18N

        dishIsVegetarianText.setText(resourceMap.getString("dishIsVegetarianText.text")); // NOI18N
        dishIsVegetarianText.setName("dishIsVegetarianText"); // NOI18N

        dishisSpicyText.setText(resourceMap.getString("dishisSpicyText.text")); // NOI18N
        dishisSpicyText.setName("dishisSpicyText"); // NOI18N

        dishDescriptionScrollPane.setName("dishDescriptionScrollPane"); // NOI18N

        dishDescriptionTextArea.setColumns(20);
        dishDescriptionTextArea.setEditable(false);
        dishDescriptionTextArea.setLineWrap(true);
        dishDescriptionTextArea.setRows(3);
        dishDescriptionTextArea.setName("dishDescriptionTextArea"); // NOI18N
        dishDescriptionScrollPane.setViewportView(dishDescriptionTextArea);

        javax.swing.GroupLayout dishDescriptionAreaLayout = new javax.swing.GroupLayout(dishDescriptionArea);
        dishDescriptionArea.setLayout(dishDescriptionAreaLayout);
        dishDescriptionAreaLayout.setHorizontalGroup(
            dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishDescriptionAreaLayout.createSequentialGroup()
                .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dishDescriptionLabel)
                    .addComponent(dishDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dishContainsGlutenLabel)
                    .addComponent(dishContainsDairyLabel)
                    .addComponent(dishIsVegetarianLabel)
                    .addComponent(dishIsSpicyLabel)
                    .addComponent(dishContainsNutsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dishisSpicyText)
                    .addComponent(dishContainsNutsText)
                    .addComponent(dishIsVegetarianText)
                    .addComponent(dishContainsGlutenText)
                    .addComponent(dishContainsDairyText))
                .addContainerGap())
        );
        dishDescriptionAreaLayout.setVerticalGroup(
            dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishDescriptionAreaLayout.createSequentialGroup()
                .addComponent(dishDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dishDescriptionAreaLayout.createSequentialGroup()
                        .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dishContainsGlutenLabel)
                            .addComponent(dishContainsGlutenText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dishContainsNutsLabel)
                            .addComponent(dishContainsNutsText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dishContainsDairyLabel)
                            .addComponent(dishContainsDairyText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dishIsVegetarianLabel)
                            .addComponent(dishIsVegetarianText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dishDescriptionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dishisSpicyText)
                            .addComponent(dishIsSpicyLabel)))
                    .addComponent(dishDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        javax.swing.GroupLayout dishSelectionAreaLayout = new javax.swing.GroupLayout(dishSelectionArea);
        dishSelectionArea.setLayout(dishSelectionAreaLayout);
        dishSelectionAreaLayout.setHorizontalGroup(
            dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDishButton)
                    .addComponent(dishSelectionSectionLabel)
                    .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dishSearchTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(dishDescriptionArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extrasSearchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(extrasSelectionSectionLabel))
                .addContainerGap())
        );
        dishSelectionAreaLayout.setVerticalGroup(
            dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishSelectionAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dishSelectionSectionLabel)
                    .addComponent(extrasSelectionSectionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dishSearchTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addComponent(extrasSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dishDescriptionArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDishButton)
                .addContainerGap())
        );

        orderCreationUIVerticalSplitPane.setTopComponent(dishSelectionArea);

        orderOverviewUI.setName("orderOverviewUI"); // NOI18N

        orderContentsTableScrollPane.setName("orderContentsTableScrollPane"); // NOI18N

        orderContentsTable.setAutoCreateRowSorter(true);
        orderContentsTable.setModel(new DefaultTableModel());
        orderContentsTable.setColumnSelectionAllowed(true);
        orderContentsTable.setName("orderContentsTable"); // NOI18N
        orderContentsTable.getTableHeader().setReorderingAllowed(false);
        orderContentsTableScrollPane.setViewportView(orderContentsTable);
        orderContentsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        orderCommentsTextAreaLabel.setText(resourceMap.getString("orderCommentsTextAreaLabel.text")); // NOI18N
        orderCommentsTextAreaLabel.setName("orderCommentsTextAreaLabel"); // NOI18N

        orderCommentsTextAreaScrollPane.setName("orderCommentsTextAreaScrollPane"); // NOI18N

        orderCommentsTextArea.setColumns(20);
        orderCommentsTextArea.setLineWrap(true);
        orderCommentsTextArea.setRows(2);
        orderCommentsTextArea.setName("orderCommentsTextArea"); // NOI18N
        orderCommentsTextAreaScrollPane.setViewportView(orderCommentsTextArea);

        resetOrderButton.setText(resourceMap.getString("resetOrderButton.text")); // NOI18N
        resetOrderButton.setName("resetOrderButton"); // NOI18N

        confirmOrderButton.setText(resourceMap.getString("confirmOrderButton.text")); // NOI18N
        confirmOrderButton.setName("confirmOrderButton"); // NOI18N

        deleteSelectedOrderDishButton.setText(resourceMap.getString("deleteSelectedOrderDishButton.text")); // NOI18N
        deleteSelectedOrderDishButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
        deleteSelectedOrderDishButton.setName("deleteSelectedOrderDishButton"); // NOI18N

        duplicateSelectedOrderDishButton.setText(resourceMap.getString("duplicateSelectedOrderDishButton.text")); // NOI18N
        duplicateSelectedOrderDishButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
        duplicateSelectedOrderDishButton.setName("duplicateSelectedOrderDishButton"); // NOI18N

        deliveryMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Delivery at home", "Pick up at restaurant"}));
        deliveryMethodComboBox.setName("deliveryMethodComboBox"); // NOI18N

        javax.swing.GroupLayout orderOverviewUILayout = new javax.swing.GroupLayout(orderOverviewUI);
        orderOverviewUI.setLayout(orderOverviewUILayout);
        orderOverviewUILayout.setHorizontalGroup(
            orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                        .addComponent(orderCommentsTextAreaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                        .addComponent(deliveryMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duplicateSelectedOrderDishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSelectedOrderDishButton))
                    .addComponent(orderCommentsTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                        .addComponent(resetOrderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmOrderButton)))
                .addContainerGap())
            .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        orderOverviewUILayout.setVerticalGroup(
            orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteSelectedOrderDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duplicateSelectedOrderDishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deliveryMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(orderCommentsTextAreaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmOrderButton)
                    .addComponent(resetOrderButton))
                .addContainerGap())
        );

        orderCreationUIVerticalSplitPane.setRightComponent(orderOverviewUI);

        javax.swing.GroupLayout orderCreationUILayout = new javax.swing.GroupLayout(orderCreationUI);
        orderCreationUI.setLayout(orderCreationUILayout);
        orderCreationUILayout.setHorizontalGroup(
            orderCreationUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderCreationUIVerticalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        orderCreationUILayout.setVerticalGroup(
            orderCreationUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderCreationUIVerticalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        mainSplitPane.setRightComponent(orderCreationUI);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>
    // Variables declaration - do not modify
    public static final javax.swing.JButton addDishButton = new javax.swing.JButton();
    public static final javax.swing.JButton changeCustomerButton = new javax.swing.JButton();
    public static final javax.swing.JButton confirmOrderButton = new javax.swing.JButton();
    public static final javax.swing.JScrollPane customerInformationScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTextArea customerInformationTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JList customerList = new javax.swing.JList();
    public static final javax.swing.JScrollPane customerListScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel customerLookupUI = new javax.swing.JPanel();
    public static final javax.swing.JButton deleteCustomerButton = new javax.swing.JButton();
    public static final javax.swing.JButton deleteSelectedOrderDishButton = new javax.swing.JButton();
    public static final javax.swing.JComboBox deliveryMethodComboBox = new javax.swing.JComboBox();
    public static final javax.swing.JLabel dishContainsDairyLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishContainsDairyText = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishContainsGlutenLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishContainsGlutenText = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishContainsNutsLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishContainsNutsText = new javax.swing.JLabel();
    public static final javax.swing.JPanel dishDescriptionArea = new javax.swing.JPanel();
    public static final javax.swing.JLabel dishDescriptionLabel = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane dishDescriptionScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTextArea dishDescriptionTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JLabel dishIsSpicyLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishIsVegetarianLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishIsVegetarianText = new javax.swing.JLabel();
    public static final javax.swing.JTextField dishSearchTextBox = new javax.swing.JTextField();
    public static final javax.swing.JPanel dishSelectionArea = new javax.swing.JPanel();
    public static final javax.swing.JList dishSelectionList = new javax.swing.JList();
    public static final javax.swing.JLabel dishSelectionSectionLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel dishisSpicyText = new javax.swing.JLabel();
    public static final javax.swing.JButton duplicateSelectedOrderDishButton = new javax.swing.JButton();
    public static final javax.swing.JTextField extrasSearchTextField = new javax.swing.JTextField();
    public static final javax.swing.JList extrasSelectionList = new javax.swing.JList();
    public static final javax.swing.JLabel extrasSelectionSectionLabel = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
    public static final javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
    public static final javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel mainPanel = new javax.swing.JPanel();
    public static final javax.swing.JSplitPane mainSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JButton newCustomerButton = new javax.swing.JButton();
    public static final javax.swing.JTextArea orderCommentsTextArea = new javax.swing.JTextArea();
    public static final javax.swing.JLabel orderCommentsTextAreaLabel = new javax.swing.JLabel();
    public static final javax.swing.JScrollPane orderCommentsTextAreaScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JTable orderContentsTable = new javax.swing.JTable(){
        public boolean isCellEditable(int rowIndex, int colIndex) {
            return false; //Disallow the editing of any cell
        }
    };
    public static final javax.swing.JScrollPane orderContentsTableScrollPane = new javax.swing.JScrollPane();
    public static final javax.swing.JPanel orderCreationUI = new javax.swing.JPanel();
    public static final javax.swing.JSplitPane orderCreationUIVerticalSplitPane = new javax.swing.JSplitPane();
    public static final javax.swing.JPanel orderOverviewUI = new javax.swing.JPanel();
    public static final javax.swing.JButton resetOrderButton = new javax.swing.JButton();
    public static final javax.swing.JTextField searchCustomerTextArea = new javax.swing.JTextField();
    public static final javax.swing.JButton selectCustomerButton = new javax.swing.JButton();
    // End of variables declaration
}
