/**
 * This package contains classes containing code automatically
 * generated by the NetBeans IDE.<p>
 * The classes hold all the components of the program as 
 * public static final fields. There is one View class for each
 * of the views of the program. The components are initialized by
 * the classes of the {@link pizzaProgram.gui} package.
 */
package pizzaProgram.gui.views;