/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrderViewNew.java
 *
 * Created on 21.okt.2011, 13:05:40
 */
package pizzaprogram.gui.views;

/**
 *
 * @author Bart
 */
public class OrderView extends javax.swing.JPanel {

    /** Creates new form OrderViewNew */
    public OrderView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainSplitPane = new javax.swing.JSplitPane();
        customerLookupUI = new javax.swing.JPanel();
        newCustomerButton = new javax.swing.JButton();
        searchCustomerTextArea = new javax.swing.JTextField();
        searchCustomerSearchButton = new javax.swing.JButton();
        customerListScrollPane = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList();
        customerInformationScrollPane = new javax.swing.JScrollPane();
        customerInformationTextArea = new javax.swing.JTextArea();
        selectCustomerButton = new javax.swing.JButton();
        orderCreationUI = new javax.swing.JPanel();
        orderCreationUIVerticalSplitPane = new javax.swing.JSplitPane();
        dishSelectionArea = new javax.swing.JPanel();
        dishTableScrollPane = new javax.swing.JScrollPane();
        dishTable = new javax.swing.JTable();
        addDishButton = new javax.swing.JButton();
        orderOverviewUI = new javax.swing.JPanel();
        orderContentsTableScrollPane = new javax.swing.JScrollPane();
        orderContentsTable = new javax.swing.JTable();
        orderCommentsTextAreaLabel = new javax.swing.JLabel();
        orderCommentsTextAreaScrollPane = new javax.swing.JScrollPane();
        orderCommentsTextArea = new javax.swing.JTextArea();
        resetOrderButton = new javax.swing.JButton();
        confirmOrderButton = new javax.swing.JButton();
        deleteSelectedOrderDishButton = new javax.swing.JButton();
        duplicateSelectedOrderDishButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        mainPanel.setName("mainPanel"); // NOI18N

        mainSplitPane.setDividerLocation(200);
        mainSplitPane.setDoubleBuffered(true);
        mainSplitPane.setName("mainSplitPane"); // NOI18N

        customerLookupUI.setName("customerLookupUI"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(pizzaprogram.core.PizzaProgram.class).getContext().getResourceMap(OrderView.class);
        newCustomerButton.setText(resourceMap.getString("newCustomerButton.text")); // NOI18N
        newCustomerButton.setName("newCustomerButton"); // NOI18N

        searchCustomerTextArea.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchCustomerTextArea.setName("searchCustomerTextArea"); // NOI18N

        searchCustomerSearchButton.setText(resourceMap.getString("searchCustomerSearchButton.text")); // NOI18N
        searchCustomerSearchButton.setName("searchCustomerSearchButton"); // NOI18N

        customerListScrollPane.setName("customerListScrollPane"); // NOI18N

        customerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        customerList.setName("customerList"); // NOI18N
        customerListScrollPane.setViewportView(customerList);

        customerInformationScrollPane.setName("customerInformationScrollPane"); // NOI18N

        customerInformationTextArea.setColumns(20);
        customerInformationTextArea.setRows(4);
        customerInformationTextArea.setFocusable(false);
        customerInformationTextArea.setName("customerInformationTextArea"); // NOI18N
        customerInformationScrollPane.setViewportView(customerInformationTextArea);

        selectCustomerButton.setText(resourceMap.getString("selectCustomerButton.text")); // NOI18N
        selectCustomerButton.setName("selectCustomerButton"); // NOI18N

        javax.swing.GroupLayout customerLookupUILayout = new javax.swing.GroupLayout(customerLookupUI);
        customerLookupUI.setLayout(customerLookupUILayout);
        customerLookupUILayout.setHorizontalGroup(
            customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLookupUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLookupUILayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(selectCustomerButton))
                    .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(newCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLookupUILayout.createSequentialGroup()
                        .addComponent(searchCustomerTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchCustomerSearchButton))
                    .addComponent(customerInformationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        customerLookupUILayout.setVerticalGroup(
            customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLookupUILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerLookupUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchCustomerTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCustomerSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerInformationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCustomerButton)
                .addContainerGap())
        );

        mainSplitPane.setLeftComponent(customerLookupUI);

        orderCreationUI.setName("orderCreationUI"); // NOI18N

        orderCreationUIVerticalSplitPane.setDividerLocation(200);
        orderCreationUIVerticalSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        orderCreationUIVerticalSplitPane.setName("orderCreationUIVerticalSplitPane"); // NOI18N

        dishSelectionArea.setName("dishSelectionArea"); // NOI18N

        dishTableScrollPane.setName("dishTableScrollPane"); // NOI18N

        dishTable.setAutoCreateRowSorter(true);
        dishTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pizza", "Extras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dishTable.setName("dishTable"); // NOI18N
        dishTable.getTableHeader().setReorderingAllowed(false);
        dishTableScrollPane.setViewportView(dishTable);

        addDishButton.setText(resourceMap.getString("addDishButton.text")); // NOI18N
        addDishButton.setName("addDishButton"); // NOI18N

        javax.swing.GroupLayout dishSelectionAreaLayout = new javax.swing.GroupLayout(dishSelectionArea);
        dishSelectionArea.setLayout(dishSelectionAreaLayout);
        dishSelectionAreaLayout.setHorizontalGroup(
            dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dishSelectionAreaLayout.createSequentialGroup()
                .addComponent(addDishButton)
                .addGap(652, 652, 652))
            .addComponent(dishTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        dishSelectionAreaLayout.setVerticalGroup(
            dishSelectionAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dishSelectionAreaLayout.createSequentialGroup()
                .addComponent(dishTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDishButton))
        );

        orderCreationUIVerticalSplitPane.setTopComponent(dishSelectionArea);

        orderOverviewUI.setName("orderOverviewUI"); // NOI18N

        orderContentsTableScrollPane.setName("orderContentsTableScrollPane"); // NOI18N

        orderContentsTable.setAutoCreateRowSorter(true);
        orderContentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pizza", "Extras"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderContentsTable.setColumnSelectionAllowed(true);
        orderContentsTable.setName("orderContentsTable"); // NOI18N
        orderContentsTableScrollPane.setViewportView(orderContentsTable);

        orderCommentsTextAreaLabel.setName("orderCommentsTextAreaLabel"); // NOI18N

        orderCommentsTextAreaScrollPane.setName("orderCommentsTextAreaScrollPane"); // NOI18N

        orderCommentsTextArea.setColumns(20);
        orderCommentsTextArea.setLineWrap(true);
        orderCommentsTextArea.setRows(2);
        orderCommentsTextArea.setName("orderCommentsTextArea"); // NOI18N
        orderCommentsTextAreaScrollPane.setViewportView(orderCommentsTextArea);

        resetOrderButton.setText(resourceMap.getString("resetOrderButton.text")); // NOI18N
        resetOrderButton.setName("resetOrderButton"); // NOI18N

        confirmOrderButton.setText(resourceMap.getString("confirmOrderButton.text")); // NOI18N
        confirmOrderButton.setName("confirmOrderButton"); // NOI18N

        deleteSelectedOrderDishButton.setText(resourceMap.getString("deleteSelectedOrderDishButton.text")); // NOI18N
        deleteSelectedOrderDishButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
        deleteSelectedOrderDishButton.setName("deleteSelectedOrderDishButton"); // NOI18N

        duplicateSelectedOrderDishButton.setText(resourceMap.getString("duplicateSelectedOrderDishButton.text")); // NOI18N
        duplicateSelectedOrderDishButton.setMargin(new java.awt.Insets(0, 10, 0, 10));
        duplicateSelectedOrderDishButton.setName("duplicateSelectedOrderDishButton"); // NOI18N

        javax.swing.GroupLayout orderOverviewUILayout = new javax.swing.GroupLayout(orderOverviewUI);
        orderOverviewUI.setLayout(orderOverviewUILayout);
        orderOverviewUILayout.setHorizontalGroup(
            orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                        .addComponent(orderCommentsTextAreaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                        .addComponent(duplicateSelectedOrderDishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSelectedOrderDishButton))
                    .addComponent(orderCommentsTextAreaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                        .addComponent(resetOrderButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmOrderButton)))
                .addContainerGap())
            .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        orderOverviewUILayout.setVerticalGroup(
            orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderOverviewUILayout.createSequentialGroup()
                .addComponent(orderContentsTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteSelectedOrderDishButton)
                        .addComponent(duplicateSelectedOrderDishButton))
                    .addComponent(orderCommentsTextAreaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderCommentsTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderOverviewUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmOrderButton)
                    .addComponent(resetOrderButton))
                .addContainerGap())
        );

        orderCreationUIVerticalSplitPane.setRightComponent(orderOverviewUI);

        javax.swing.GroupLayout orderCreationUILayout = new javax.swing.GroupLayout(orderCreationUI);
        orderCreationUI.setLayout(orderCreationUILayout);
        orderCreationUILayout.setHorizontalGroup(
            orderCreationUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderCreationUIVerticalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        orderCreationUILayout.setVerticalGroup(
            orderCreationUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderCreationUIVerticalSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        mainSplitPane.setRightComponent(orderCreationUI);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDishButton;
    private javax.swing.JButton confirmOrderButton;
    private javax.swing.JScrollPane customerInformationScrollPane;
    private javax.swing.JTextArea customerInformationTextArea;
    private javax.swing.JList customerList;
    private javax.swing.JScrollPane customerListScrollPane;
    private javax.swing.JPanel customerLookupUI;
    private javax.swing.JButton deleteSelectedOrderDishButton;
    private javax.swing.JPanel dishSelectionArea;
    private javax.swing.JTable dishTable;
    private javax.swing.JScrollPane dishTableScrollPane;
    private javax.swing.JButton duplicateSelectedOrderDishButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JButton newCustomerButton;
    private javax.swing.JTextArea orderCommentsTextArea;
    private javax.swing.JLabel orderCommentsTextAreaLabel;
    private javax.swing.JScrollPane orderCommentsTextAreaScrollPane;
    private javax.swing.JTable orderContentsTable;
    private javax.swing.JScrollPane orderContentsTableScrollPane;
    private javax.swing.JPanel orderCreationUI;
    private javax.swing.JSplitPane orderCreationUIVerticalSplitPane;
    private javax.swing.JPanel orderOverviewUI;
    private javax.swing.JButton resetOrderButton;
    private javax.swing.JButton searchCustomerSearchButton;
    private javax.swing.JTextField searchCustomerTextArea;
    private javax.swing.JButton selectCustomerButton;
    // End of variables declaration//GEN-END:variables
}
