package pizzaProgram.gui;

import java.util.ArrayList;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import pizzaProgram.dataObjects.Order;
import pizzaProgram.events.Event;
import pizzaProgram.events.EventDispatcher;
import pizzaProgram.events.EventHandler;
import pizzaProgram.events.EventType;
import pizzaProgram.gui.EventHandlers.DeliveryGUI_DeliveryViewEventHandler;
import pizzaProgram.gui.EventHandlers.DeliveryGUI_SystemEventHandler;
import pizzaProgram.gui.views.DeliveryView;
import pizzaProgram.modules.GUIModule;

/**
 * this class is for initilizing the deliverygui, since deliveryview is autogenerated and 
 * should not be edited, all initalisation and hiding/showing is handled by this class
 */
public class DeliverGUI extends GUIModule implements EventHandler {
	/**
	 * Holds a reference to the DeliveryView instance so that it can be used to display and hide it
	 */
	private DeliveryView deliverView;
	/**
	 * A reference to the program's main window
	 */
	private ProgramWindow programWindow;
	/**
	 * A list of the orders that are currently being displayed in the delivery view
	 */
	public ArrayList<Order> currentOrderList;
	/**
	 * The order that is currently being displayed in the delivery GUI
	 */
	public Order currentOrder;
	
	/**
	 * Holds a reference to the delivery view event handler for later reference
	 */
	private DeliveryGUI_DeliveryViewEventHandler deliveryViewEventHandler;

	/**
	 * The constructor, creates the deliveryView Jpanel, creates event handlers and registers the JPanel at the program's main window
	 * @param mainWindow
	 * @param eventDispatcher
	 */
	public DeliverGUI(ProgramWindow mainWindow, EventDispatcher eventDispatcher) {
		super(eventDispatcher);

		eventDispatcher.addEventListener(this, EventType.COOK_GUI_REQUESTED);
		eventDispatcher.addEventListener(this, EventType.ORDER_GUI_REQUESTED);
		eventDispatcher.addEventListener(this, EventType.DELIVERY_GUI_REQUESTED);
		this.deliverView = new DeliveryView();
		mainWindow.addJPanel(this.deliverView);
		this.programWindow = mainWindow;
		hide();
		this.setupComponents();
		this.deliveryViewEventHandler = new DeliveryGUI_DeliveryViewEventHandler(this);
		new DeliveryGUI_SystemEventHandler(eventDispatcher, this);
	}

	/**
	 * initialises all components and fills them with default data
	 */
	private void setupComponents() {
		DefaultTableModel tableModel = (DefaultTableModel) DeliveryView.activeOrdersTable.getModel();
		tableModel.addColumn("ID");
		tableModel.addColumn("Status");
		tableModel.addColumn("Tid mottatt");
		tableModel.addColumn("Leveringsmetode");
		DeliveryView.activeOrdersTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		tableModel = (DefaultTableModel) DeliveryView.orderContentsTable.getModel();
		tableModel.addColumn("Rett");
		tableModel.addColumn("Tilbehør");
		tableModel.addColumn("Pris for retter");
		DeliveryView.showReceiptButton.setEnabled(false);
	}

	/**
	 * Shows the deliverygui
	 */
	@Override
	public void show() {
		this.programWindow.showPanel(this.deliverView);
		this.dispatchEvent(new Event<Object>(EventType.DATABASE_UPDATE_DELIVERY_GUI_SEND_ALL_ORDERS));
	}

	/**
	 * Hides the deliverygui
	 */
	@Override
	public void hide() {
		this.programWindow.hidePanel(this.deliverView);

	}
	
	/**
	 * Handles events that are directed at the delivery GUI module, and calls the appropiate internal event handling functions
	 */
	@Override
	public void handleEvent(Event<?> event) {
		if (event.eventType.equals(EventType.DELIVERY_GUI_REQUESTED)) {
			show();
		} else if (event.eventType.equals(EventType.DATA_REFRESH_REQUESTED)) {
			if(this.programWindow.panelIsCurrentlyVisible(this.deliverView))
			{
				this.deliveryViewEventHandler.showOrdersBasedOnSearchBox();
			}
		} 
	}
}