package pizzaProgram.gui.EventHandlers;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;

import javax.swing.DefaultListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import pizzaProgram.dataObjects.Extra;
import pizzaProgram.dataObjects.Order;
import pizzaProgram.dataObjects.OrderDish;
import pizzaProgram.events.Event;
import pizzaProgram.events.EventType;
import pizzaProgram.gui.CookGUI;
import pizzaProgram.gui.views.CookView;
/**
 * Handles all events generated by user interaction with the Cook GUI view.
 * @author Bart
 *
 */
public class CookGUI_CookViewEventHandler extends ComponentEventHandler implements ActionListener {
	/**
	 * A reference to the main Cook GUI module
	 */
	private CookGUI cookGUI;
	
	/**
	 * Registers all appropiate event handlers at the different components in the cook view
	 * @param cookGUI A reference to the main CookGUI module
	 */
	public CookGUI_CookViewEventHandler(CookGUI cookGUI) {
		super(cookGUI);
		this.cookGUI = cookGUI;
		this.resetUI();
		this.addEventListeners();
	}
	
	/**
	 * Registers event listeners at the various components in the cook GUI that this class handles
	 */
	private void addEventListeners(){
		CookView.orderDetailsTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				handleOrderSelection(e);
			}
		});
		
		CookView.orderSearchTextPane.addFocusListener(new FocusListener(){public void focusLost(FocusEvent arg0) {}
		public void focusGained(FocusEvent arg0) {
			handleSearchBoxSelection();}});
		
		CookView.markOrderInProgressButton.addActionListener(this);
		this.registerEventType(CookView.markOrderInProgressButton, "markOrderAsInProgress");
		
		CookView.markOrderCompletedButton.addActionListener(this);
		this.registerEventType(CookView.markOrderCompletedButton, "markOrderCompleted");
		
		CookView.orderSearchTextPane.addKeyListener(new KeyListener(){
			public void keyPressed(KeyEvent arg0) {}
			public void keyTyped(KeyEvent arg0) {}
			public void keyReleased(KeyEvent arg0) {
				showOrdersBasedOnSearchBoxContents();
			}
		});
	}

	/**
	 * Handles events from the Cook view, and calls the appropiate event handling function
	 */
	public void actionPerformed(ActionEvent event) {
		if (this.getEventNameByComponent((Component) event.getSource()).equals("markOrderAsInProgress")) {
			this.markOrderAsInProgress();
		} else if (this.getEventNameByComponent((Component) event.getSource()).equals("markOrderCompleted")) {
			this.markOrderCompleted();
		} else if (this.getEventNameByComponent((Component) event.getSource()).equals("searchOrders")) {
			this.searchOrdersBySearchBoxQuery();
		}
	}
	
	/**
	 * Shows all customers in the cook gui if the search box is empty, otherwise it searches for the contents of the search box in the database
	 */
	public void showOrdersBasedOnSearchBoxContents()
	{
		if(CookView.orderSearchTextPane.getText().trim().isEmpty()) {
			showAllOrders();
		} else {
			searchOrdersBySearchBoxQuery();
		}
	}
	
	
	/**
	 * Automatically selects all text in the order search text box if the user gives it focus.
	 */
	protected void handleSearchBoxSelection() {
		CookView.orderSearchTextPane.setSelectionStart(0);
		CookView.orderSearchTextPane.setSelectionEnd(CookView.orderSearchTextPane.getText().length());
	}
	
	/**
	 * Shows all orders that have not yet finished cooking (which it fetches from the database)
	 */
	private void showAllOrders(){
		this.dispatchEvent(new Event<Object>(EventType.DATABASE_UPDATE_COOK_GUI_SEND_ALL_ORDERS));
	}
	
	/**
	 * Marks the currently selected order as completed
	 */
	private void markOrderCompleted() {
		this.dispatchEvent(new Event<Order>(EventType.DATABASE_MARK_ORDER_FINISHED_COOKING, this.cookGUI.currentSelectedOrder));
		this.resetUI();
		this.updateCurrentOrder();
	}
	
	/**
	 * Marks the currently selected order as in progress
	 */
	private void markOrderAsInProgress() {
		this.dispatchEvent(new Event<Order>(EventType.DATABASE_MARK_ORDER_IN_PROGRESS, this.cookGUI.currentSelectedOrder));
		this.updateCurrentOrder();
	}
	
	/**
	 * Updates the current order by doing a refresh with the database. It will refresh by the contents of the order search box; it will search again when there is text written in the search box, or refresh all orders if it is empty
	 */
	private void updateCurrentOrder() {
		int selectedIndex = CookView.orderDetailsTable.getSelectionModel().getMinSelectionIndex();
		showAllOrders();
		if(selectedIndex == -1){
			return;
		}
		CookView.orderDetailsTable.getSelectionModel().setLeadSelectionIndex(selectedIndex);
		Order order = this.cookGUI.currentOrderList.get(selectedIndex);
		this.cookGUI.currentSelectedOrder = order;
		this.showOrder(order);
		if(CookView.orderSearchTextPane.getText().isEmpty()){
			showAllOrders();
		}else{
			searchOrdersBySearchBoxQuery();
		}
	}
	
	/**
	 * Searches the database for orders by the text written in the order search box, then updates vthe order list
	 */
	private void searchOrdersBySearchBoxQuery() {
		this.dispatchEvent(new Event<String>(EventType.DATABASE_UPDATE_COOK_GUI_SEARCH_ORDERS_BY_KEYWORDS, CookView.orderSearchTextPane.getText().trim()));
	}
	
	/**
	 * Resets the UI to its initial state
	 */
	private void resetUI(){
		CookView.markOrderCompletedButton.setEnabled(false);
		CookView.markOrderInProgressButton.setEnabled(false);
		DefaultTableModel tableModel = (DefaultTableModel)CookView.currentOrderTable.getModel();
		tableModel.setNumRows(0);
		tableModel = (DefaultTableModel)CookView.orderDetailsTable.getModel();
		tableModel.setNumRows(0);
		CookView.orderCommentsTextArea.setText("");
	}
	
	/**
	 * Handles the event of a user selecting an order in the order list
	 * @param event The event dispatched by the java AWT thread
	 */
	private void handleOrderSelection(ListSelectionEvent event) {
		int selectedIndex = ((DefaultListSelectionModel)event.getSource()).getMinSelectionIndex();
		if(selectedIndex == -1){
			return;
		}
		Order order = this.cookGUI.currentOrderList.get(selectedIndex);
		this.cookGUI.currentSelectedOrder = order;
		this.showOrder(order);
	}
	
	/**
	 * Shows an order in the cook GUI
	 * @param order The order to display
	 */
	private void showOrder(Order order) {
		DefaultTableModel tableModel = (DefaultTableModel) CookView.currentOrderTable.getModel();
		tableModel.setRowCount(0);
		String extrasString;
		for(OrderDish dish : order.getOrderedDishes()){
			extrasString = generateExtrasStringFromExtrasList(dish.getExtras());
			tableModel.addRow(new Object[]{dish.dish.name, extrasString});
		}
		CookView.orderCommentsTextArea.setText(order.comment);
		this.enableOrderMarkButtons(order);
	}
	
	/**
	 * Enables/disables the "mark order in progress" and "Mark order completed" buttons in the cook GUI according to the state of the passed Order instance 
	 * @param order The Order instance to use
	 */
	private void enableOrderMarkButtons(Order order) {
		if(order.status.equals(Order.REGISTERED)){
			CookView.markOrderCompletedButton.setEnabled(false);
			CookView.markOrderInProgressButton.setEnabled(true);
		}
		else if (order.status.equals(Order.BEING_COOKED)){
			CookView.markOrderCompletedButton.setEnabled(true);
			CookView.markOrderInProgressButton.setEnabled(false);
		}
		else {
			CookView.markOrderCompletedButton.setEnabled(false);
			CookView.markOrderInProgressButton.setEnabled(false);
		}
	}
	
	/**
	 * Generates a single string from a list of Extra instances that represents that list of extras
	 * @param extrasList An ArrayList containing Extra instances
	 * @return A string representing the input list
	 */
	private String generateExtrasStringFromExtrasList(ArrayList<Extra> extrasList){
		String extrasString = "";
		int counter = 0;
		for(Extra extra : extrasList){
			if(counter != 0){
				extrasString += ", ";
			}
			counter = 1;
			extrasString += extra.name;
		}
		return extrasString;
	}

}//END
